//! `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs` -- the Berserker definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:35`.
pub static D170_0: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "10% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 96406,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:37`.
pub static D170_1: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "20% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 96406,
    max_gw2_build: 97950,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:39`.
pub static D170_2: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "20% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 97950,
    max_gw2_build: 133322,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:41`.
pub static D170_3: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "25% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 133322,
    max_gw2_build: 147734,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:43`.
pub static D170_4: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "20% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 147734,
    max_gw2_build: 157732,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:45`.
pub static D170_5: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "15% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 157732,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:47`.
pub static D170_6: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "15% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 97950,
    max_gw2_build: 135242,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:49`.
pub static D170_7: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "10% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 135242,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BloodyRoar = 170` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/BerserkerHelper.cs:51`.
pub static D170_8: DamageModifierDef = DamageModifierDef {
    id: 170,
    name: "Bloody Roar",
    icon: "https://render.guildwars2.com/file/382002B6265A4D4F5EC305BD09484B0CEC69ACC9/1029971.png",
    description: "10% while in berserk",
    source: ModSource::Spec("Berserker"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[29502], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (9).
pub static DEFS: &[&DamageModifierDef] = &[
    &D170_0,
    &D170_1,
    &D170_2,
    &D170_3,
    &D170_4,
    &D170_5,
    &D170_6,
    &D170_7,
    &D170_8,
];
