//! Gear (`GearDamageModifiers.cs`) -- runes, sigils and relics.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_ScholarRune = 3` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:15`.
pub static D3_0: DamageModifierDef = DamageModifierDef {
    id: 3,
    name: "Scholar Rune",
    icon: "https://render.guildwars2.com/file/4378ABC0415950DAC6A05C76920392D72E242EC2/220736.png",
    description: "5% if hp >=90%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 93543,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ScholarRune = 3` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:17`.
pub static D3_1: DamageModifierDef = DamageModifierDef {
    id: 3,
    name: "Scholar Rune",
    icon: "https://render.guildwars2.com/file/4378ABC0415950DAC6A05C76920392D72E242EC2/220736.png",
    description: "10% if hp >=90%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 93543,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_EagleRune = 4` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:19`.
pub static D4_0: DamageModifierDef = DamageModifierDef {
    id: 4,
    name: "Eagle Rune",
    icon: "https://render.guildwars2.com/file/2966CB3D97E85EB0E4C33AFB6D1FB63D7304EC97/220700.png",
    description: "10% if target <50% HP",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::AgainstUnderFifty],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 93543,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_EagleRune = 4` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:21`.
pub static D4_1: DamageModifierDef = DamageModifierDef {
    id: 4,
    name: "Eagle Rune",
    icon: "https://render.guildwars2.com/file/2966CB3D97E85EB0E4C33AFB6D1FB63D7304EC97/220700.png",
    description: "6% if target <50% HP",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 6.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::AgainstUnderFifty],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 93543,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ThiefRune = 5` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:23`.
pub static D5_0: DamageModifierDef = DamageModifierDef {
    id: 5,
    name: "Thief Rune",
    icon: "https://render.guildwars2.com/file/997AEFF0927F640DE515B4DA516911B3B3B6B9EA/220731.png",
    description: "10% while flanking",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Flanking],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 147734,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StrengthRune = 41` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:27`.
pub static D41_0: DamageModifierDef = DamageModifierDef {
    id: 41,
    name: "Strength Rune",
    icon: "https://render.guildwars2.com/file/F33F44776DFCB0D75B48005904E3C75456C4F5FA/220644.png",
    description: "5% under might",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FireRune = 42` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:29`.
pub static D42_0: DamageModifierDef = DamageModifierDef {
    id: 42,
    name: "Fire Rune",
    icon: "https://render.guildwars2.com/file/6967534DA6E09150241DC411B0F4A4B415520FF7/220702.png",
    description: "10% under fire aura",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[5677], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 93543,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RageRune = 43` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:37`.
pub static D43_0: DamageModifierDef = DamageModifierDef {
    id: 43,
    name: "Rage Rune",
    icon: "https://render.guildwars2.com/file/5F65FDA9D721B6BA5654E5ED29A42B01C04DF2DA/220719.png",
    description: "5% under fury",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[725], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheThief = 44` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:57`.
pub static D44_0: DamageModifierDef = DamageModifierDef {
    id: 44,
    name: "Relic of the Thief",
    icon: "https://render.guildwars2.com/file/3523AC08EB04347CF371E9A91F4B985D12FB4ED3/3122371.png",
    description: "1% per stack",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[70767], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfFireworks = 312` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:58`.
pub static D312_0: DamageModifierDef = DamageModifierDef {
    id: 312,
    name: "Relic of Fireworks",
    icon: "https://render.guildwars2.com/file/2999CCF7C94267B2EE3DDA7459050864622927C9/3122349.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[69855], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 151966,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfFireworks = 312` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:59`.
pub static D312_1: DamageModifierDef = DamageModifierDef {
    id: 312,
    name: "Relic of Fireworks",
    icon: "https://render.guildwars2.com/file/2999CCF7C94267B2EE3DDA7459050864622927C9/3122349.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[69855], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 151966,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfFireworks = 312` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:60`.
pub static D312_2: DamageModifierDef = DamageModifierDef {
    id: 312,
    name: "Relic of Fireworks",
    icon: "https://render.guildwars2.com/file/2999CCF7C94267B2EE3DDA7459050864622927C9/3122349.png",
    description: "7%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[69855], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 151966,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheBrawler = 46` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:61`.
pub static D46_0: DamageModifierDef = DamageModifierDef {
    id: 46,
    name: "Relic of the Brawler",
    icon: "https://render.guildwars2.com/file/2B5297A932F55DA3BDDD0A39C9CB0D9CF70244A1/3122334.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[70913], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheDeadeye = 47` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:62`.
pub static D47_0: DamageModifierDef = DamageModifierDef {
    id: 47,
    name: "Relic of the Deadeye",
    icon: "https://render.guildwars2.com/file/060151B961CE56CB9546E7B6AF33B0A318426372/3122342.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[70282], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheWeaver = 48` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:63`.
pub static D48_0: DamageModifierDef = DamageModifierDef {
    id: 48,
    name: "Relic of the Weaver",
    icon: "https://render.guildwars2.com/file/12997110B0509463DD9F1364A92493B2C4309BE1/3122377.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[70390], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfNourys = 45` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:64`.
pub static D45_0: DamageModifierDef = DamageModifierDef {
    id: 45,
    name: "Relic of Nourys",
    icon: "https://render.guildwars2.com/file/9B47CEBB551B7C5E7A961AB45361E292074E0823/3187632.png",
    description: "25%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[71431], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfNourys = 45` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:65`.
pub static D45_1: DamageModifierDef = DamageModifierDef {
    id: 45,
    name: "Relic of Nourys",
    icon: "https://render.guildwars2.com/file/9B47CEBB551B7C5E7A961AB45361E292074E0823/3187632.png",
    description: "15%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[71431], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheClaw = 49` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:66`.
pub static D49_0: DamageModifierDef = DamageModifierDef {
    id: 49,
    name: "Relic of the Claw",
    icon: "https://render.guildwars2.com/file/19B5DB56E495C70754A8BE3621CADC0FD7402845/3375220.png",
    description: "7% after disabling a foe",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[73955], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfMountBalrior = 314` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:67`.
pub static D314_0: DamageModifierDef = DamageModifierDef {
    id: 314,
    name: "Relic of Mount Balrior",
    icon: "https://render.guildwars2.com/file/49A8520BDB6C5A7BA90832DB9406677473A6932F/3441973.png",
    description: "15%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[74793], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfFire = 318` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:68`.
pub static D318_0: DamageModifierDef = DamageModifierDef {
    id: 318,
    name: "Relic of Fire",
    icon: "https://render.guildwars2.com/file/00E5051DCC0EDD58395DF9CEA3456466EA4FD347/3592834.png",
    description: "10% under fire aura",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[5677], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 176750,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfFire = 318` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:70`.
pub static D318_1: DamageModifierDef = DamageModifierDef {
    id: 318,
    name: "Relic of Fire",
    icon: "https://render.guildwars2.com/file/00E5051DCC0EDD58395DF9CEA3456466EA4FD347/3592834.png",
    description: "7% under fire aura",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[5677], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 176750,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheDirector = 430` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:72`.
pub static D430_0: DamageModifierDef = DamageModifierDef {
    id: 430,
    name: "Relic of the Director",
    icon: "https://render.guildwars2.com/file/6FD76BA11105EC67451D9E7E1DE938C91DB3AD68/3770711.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[79640], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfBloodstone = 344` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:74`.
pub static D344_0: DamageModifierDef = DamageModifierDef {
    id: 344,
    name: "Bloodstone Fervor",
    icon: "https://render.guildwars2.com/file/A7327A7EDB4705EA05261110526D72AFEAF7DAB4/3629397.png",
    description: "15%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76326], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 183275,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfBloodstone = 344` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:76`.
pub static D344_1: DamageModifierDef = DamageModifierDef {
    id: 344,
    name: "Bloodstone Fervor",
    icon: "https://render.guildwars2.com/file/A7327A7EDB4705EA05261110526D72AFEAF7DAB4/3629397.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76326], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 183275,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfBloodstone = 344` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:78`.
pub static D344_2: DamageModifierDef = DamageModifierDef {
    id: 344,
    name: "Bloodstone Fervor",
    icon: "https://render.guildwars2.com/file/A7327A7EDB4705EA05261110526D72AFEAF7DAB4/3629397.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76326], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 183275,
    max_gw2_build: 191204,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfBloodstone = 344` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:80`.
pub static D344_3: DamageModifierDef = DamageModifierDef {
    id: 344,
    name: "Bloodstone Fervor",
    icon: "https://render.guildwars2.com/file/A7327A7EDB4705EA05261110526D72AFEAF7DAB4/3629397.png",
    description: "7%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76326], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 191204,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfBloodstone = 344` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:82`.
pub static D344_4: DamageModifierDef = DamageModifierDef {
    id: 344,
    name: "Bloodstone Fervor",
    icon: "https://render.guildwars2.com/file/A7327A7EDB4705EA05261110526D72AFEAF7DAB4/3629397.png",
    description: "10%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76326], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 191204,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheEagle = 319` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:85`.
pub static D319_0: DamageModifierDef = DamageModifierDef {
    id: 319,
    name: "Relic of the Eagle",
    icon: "https://render.guildwars2.com/file/DFF4EB43AD0803F60D105658052321A0BE1AF02C/3592832.png",
    description: "10% if target <50% HP",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::AgainstUnderFifty],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 176750,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RuneOfHoelbrak = 6` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:92`.
pub static D6_0: DamageModifierDef = DamageModifierDef {
    id: 6,
    name: "Rune of Hoelbrak",
    icon: "https://render.guildwars2.com/file/150204B4552ED82CD15204ACC7360198F51F6C13/220708.png",
    description: "-10% condition damamge",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 93543,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RuneOfTheStars = 7` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:94`.
pub static D7_0: DamageModifierDef = DamageModifierDef {
    id: 7,
    name: "Rune of the Stars",
    icon: "https://render.guildwars2.com/file/BEDDD1D249DF6FC417451E0CA25F803FA818294A/1894695.png",
    description: "-10% condition damamge",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 93543,
    max_gw2_build: 150431,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfNourys = 45` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:103`.
pub static D45_2: DamageModifierDef = DamageModifierDef {
    id: 45,
    name: "Relic of Nourys",
    icon: "https://render.guildwars2.com/file/9B47CEBB551B7C5E7A961AB45361E292074E0823/3187632.png",
    description: "-15%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[71431], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfSorrow = 50` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:104`.
pub static D50_0: DamageModifierDef = DamageModifierDef {
    id: 50,
    name: "Relic of Sorrow",
    icon: "https://render.guildwars2.com/file/F943C04CD27C463AB167FDF49F9CCC3E27F0AD18/3375222.png",
    description: "-20%",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[74410], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheFirstRevenant = 389` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:105`.
pub static D389_0: DamageModifierDef = DamageModifierDef {
    id: 389,
    name: "Relic of the First Revenant",
    icon: "https://render.guildwars2.com/file/7DA30BCFB0E0A04A5D3DFE3D25DAF142D90E1596/3709380.png",
    description: "-33% under resistance",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -33.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[26980], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheDoyen = 431` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:107`.
pub static D431_0: DamageModifierDef = DamageModifierDef {
    id: 431,
    name: "Relic of the Doyen",
    icon: "https://render.guildwars2.com/file/EF797D16D0D211064031129135C864311856CDB1/3770712.png",
    description: "-15% (not stacking with similar damage mods)",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 200514,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheDoyen = 431` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:109`.
pub static D431_1: DamageModifierDef = DamageModifierDef {
    id: 431,
    name: "Relic of the Doyen",
    icon: "https://render.guildwars2.com/file/EF797D16D0D211064031129135C864311856CDB1/3770712.png",
    description: "-10% (not stacking with similar damage mods)",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 200514,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RelicOfTheDoyen = 431` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/GearDamageModifiers.cs:111`.
pub static D431_2: DamageModifierDef = DamageModifierDef {
    id: 431,
    name: "Relic of the Doyen",
    icon: "https://render.guildwars2.com/file/EF797D16D0D211064031129135C864311856CDB1/3770712.png",
    description: "-7% (not stacking with similar damage mods)",
    source: ModSource::Gear,
    spec_specific_shared: false,
    gain_per_stack: -7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 200514,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (36).
pub static DEFS: &[&DamageModifierDef] = &[
    &D3_0,
    &D3_1,
    &D4_0,
    &D4_1,
    &D5_0,
    &D41_0,
    &D42_0,
    &D43_0,
    &D44_0,
    &D312_0,
    &D312_1,
    &D312_2,
    &D46_0,
    &D47_0,
    &D48_0,
    &D45_0,
    &D45_1,
    &D49_0,
    &D314_0,
    &D318_0,
    &D318_1,
    &D430_0,
    &D344_0,
    &D344_1,
    &D344_2,
    &D344_3,
    &D344_4,
    &D319_0,
    &D6_0,
    &D7_0,
    &D45_2,
    &D50_0,
    &D389_0,
    &D431_0,
    &D431_1,
    &D431_2,
];
