//! `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs` -- the Guardian definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_SymbolicAvenger = 107` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:134`.
pub static D107_0: DamageModifierDef = DamageModifierDef {
    id: 107,
    name: "Symbolic Avenger",
    icon: "https://render.guildwars2.com/file/C1A6EBA29894C831AAEE0D1C47080D12F9BA3AA3/1012458.png",
    description: "2% per stack",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 2.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[56890], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 97950,
    max_gw2_build: 193778,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_SymbolicAvenger = 107` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:136`.
pub static D107_1: DamageModifierDef = DamageModifierDef {
    id: 107,
    name: "Symbolic Avenger",
    icon: "https://render.guildwars2.com/file/4D3415E7E81E71E474CE6256A5C6024FAFAC0A61/1012461.png",
    description: "2% per stack",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 2.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[56890], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 193778,
    max_gw2_build: 196063,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_SymbolicAvenger = 107` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:138`.
pub static D107_2: DamageModifierDef = DamageModifierDef {
    id: 107,
    name: "Symbolic Avenger",
    icon: "https://render.guildwars2.com/file/4D3415E7E81E71E474CE6256A5C6024FAFAC0A61/1012461.png",
    description: "1% per stack",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[56890], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 196063,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FuriousFocus = 403` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:141`.
pub static D403_0: DamageModifierDef = DamageModifierDef {
    id: 403,
    name: "Furious Focus",
    icon: "https://render.guildwars2.com/file/7450B5C97FA442E5B85442A4F6EF610DC403E85A/1012453.png",
    description: "10%",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[725], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 193778,
    max_gw2_build: 196063,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FuriousFocus = 403` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:143`.
pub static D403_1: DamageModifierDef = DamageModifierDef {
    id: 403,
    name: "Furious Focus",
    icon: "https://render.guildwars2.com/file/7450B5C97FA442E5B85442A4F6EF610DC403E85A/1012453.png",
    description: "10%",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[725], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 196063,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FuriousFocus = 403` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:145`.
pub static D403_2: DamageModifierDef = DamageModifierDef {
    id: 403,
    name: "Furious Focus",
    icon: "https://render.guildwars2.com/file/7450B5C97FA442E5B85442A4F6EF610DC403E85A/1012453.png",
    description: "7%",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[725], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 196063,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Retribution = 108` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:150`.
pub static D108_0: DamageModifierDef = DamageModifierDef {
    id: 108,
    name: "Retribution",
    icon: "https://render.guildwars2.com/file/324CD720BC3A5F1B6B154BD909165F0DB03CBC0D/1012418.png",
    description: "10% under retaliation",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 115190,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Retribution = 108` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:152`.
pub static D108_1: DamageModifierDef = DamageModifierDef {
    id: 108,
    name: "Retribution",
    icon: "https://render.guildwars2.com/file/324CD720BC3A5F1B6B154BD909165F0DB03CBC0D/1012418.png",
    description: "10% under resolution",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 115190,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderAegis = 109` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:157`.
pub static D109_0: DamageModifierDef = DamageModifierDef {
    id: 109,
    name: "Unscathed Contender",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "20% under aegis",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[743], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 141374,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderAegis = 109` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:159`.
pub static D109_1: DamageModifierDef = DamageModifierDef {
    id: 109,
    name: "Unscathed Contender (Aegis)",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "7% under aegis",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[743], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 141374,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderHP = 18` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:161`.
pub static D18_0: DamageModifierDef = DamageModifierDef {
    id: 18,
    name: "Unscathed Contender (HP)",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "7% if hp >=90%",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 141374,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderAegis = 109` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:163`.
pub static D109_2: DamageModifierDef = DamageModifierDef {
    id: 109,
    name: "Unscathed Contender (Aegis)",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "7% under aegis",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[743], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderHP = 18` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:165`.
pub static D18_1: DamageModifierDef = DamageModifierDef {
    id: 18,
    name: "Unscathed Contender (HP)",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "7% if hp >=90%",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderAegis = 109` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:167`.
pub static D109_3: DamageModifierDef = DamageModifierDef {
    id: 109,
    name: "Unscathed Contender (Aegis)",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "5% under aegis",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[743], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_UnscathedContenderHP = 18` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:169`.
pub static D18_2: DamageModifierDef = DamageModifierDef {
    id: 18,
    name: "Unscathed Contender (HP)",
    icon: "https://render.guildwars2.com/file/0FF7C102A0F70E6398712C12A62B427A2B6DC05F/1012438.png",
    description: "5% if hp >=90%",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_InspiringVirtue = 313` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:175`.
pub static D313_0: DamageModifierDef = DamageModifierDef {
    id: 313,
    name: "Inspiring Virtue",
    icon: "https://render.guildwars2.com/file/3EC057E1739EF1F22815605956B46142D2669A6D/1466322.png",
    description: "10% (6s) after activating a virtue ",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[59592], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 102321,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_InspiredVirtue = 111` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:178`.
pub static D111_0: DamageModifierDef = DamageModifierDef {
    id: 111,
    name: "Inspired Virtue",
    icon: "https://render.guildwars2.com/file/6FF2B9A0099D3C75FBE97D36CBCC0470F63DFE06/1012447.png",
    description: "1% per boon",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740, 725, 1187, 30328, 717, 718, 726, 743, 1122, 719, 26980, 873], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 115190,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_InspiredVirtue = 111` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:180`.
pub static D111_1: DamageModifierDef = DamageModifierDef {
    id: 111,
    name: "Inspired Virtue",
    icon: "https://render.guildwars2.com/file/6FF2B9A0099D3C75FBE97D36CBCC0470F63DFE06/1012447.png",
    description: "0.5% per boon",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 0.5,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740, 725, 1187, 30328, 717, 718, 726, 743, 1122, 719, 26980, 873], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_InspiredVirtue = 111` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/GuardianHelper.cs:182`.
pub static D111_2: DamageModifierDef = DamageModifierDef {
    id: 111,
    name: "Inspired Virtue",
    icon: "https://render.guildwars2.com/file/6FF2B9A0099D3C75FBE97D36CBCC0470F63DFE06/1012447.png",
    description: "1% per boon",
    source: ModSource::Spec("Guardian"),
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740, 725, 1187, 30328, 717, 718, 726, 743, 1122, 719, 26980, 873], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (19).
pub static DEFS: &[&DamageModifierDef] = &[
    &D107_0,
    &D107_1,
    &D107_2,
    &D403_0,
    &D403_1,
    &D403_2,
    &D108_0,
    &D108_1,
    &D109_0,
    &D109_1,
    &D18_0,
    &D109_2,
    &D18_1,
    &D109_3,
    &D18_2,
    &D313_0,
    &D111_0,
    &D111_1,
    &D111_2,
];
