//! Consumables (`ItemDamageModifiers.cs`) -- food and utility nourishment.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_MovingBonus = 10` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:13`.
pub static D10_0: DamageModifierDef = DamageModifierDef {
    id: 10,
    name: "Moving Bonus",
    icon: "https://render.guildwars2.com/file/0D442C30D4E29832725800E22990BA111D05E0BE/219455.png",
    description: "Seaweed Salad (and the likes) – 5% while moving",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: 5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::SrcMoving],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FractalOffensive = 51` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:14`.
pub static D51_0: DamageModifierDef = DamageModifierDef {
    id: 51,
    name: "Fractal Offensive",
    icon: "https://render.guildwars2.com/file/B441F1C5F53262D54EF5CE07CF61D50E090657C4/1201539.png",
    description: "3% per stack",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: 3.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[32473], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WritOfMasterfulMalice = 211` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:15`.
pub static D211_0: DamageModifierDef = DamageModifierDef {
    id: 211,
    name: "Writ of Masterful Malice",
    icon: "https://render.guildwars2.com/file/0B09BA2F77DD6B686D7DD2F700975E4B0CAF4C1D/1201888.png",
    description: "200 condition damage if hp >=90%",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[33836], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::Condition,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WritOfMasterfufStrength = 212` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:17`.
pub static D212_0: DamageModifierDef = DamageModifierDef {
    id: 212,
    name: "Writ of Masterful Strength",
    icon: "https://render.guildwars2.com/file/01B49D4EFF3BB71D27A7B0649F0FF3E277E4D6C7/1201925.png",
    description: "200 power if hp >=90%",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[33297], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::OverNinety],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FractalDefensive = 52` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:23`.
pub static D52_0: DamageModifierDef = DamageModifierDef {
    id: 52,
    name: "Fractal Defensive",
    icon: "https://render.guildwars2.com/file/68ED78B5DFCCC79D50715A9408B2191CD0632223/1201537.png",
    description: "-5% per stack",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: -5.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[32134], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Food8 = 53` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:25`.
pub static D53_0: DamageModifierDef = DamageModifierDef {
    id: 53,
    name: "Food: -8%",
    icon: "https://render.guildwars2.com/file/779D3F0ABE5B46C09CFC57374DA8CC3A495F291C/436367.png",
    description: "-8%",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: -8.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[53384], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Food10Mult = 54` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:26`.
pub static D54_0: DamageModifierDef = DamageModifierDef {
    id: 54,
    name: "Ascended Food: -10%",
    icon: "https://render.guildwars2.com/file/779D3F0ABE5B46C09CFC57374DA8CC3A495F291C/436367.png",
    description: "-10% Multiplicative",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[57260, 69141, 57051, 57155, 57114, 57299, 57210, 57067, 57129, 57127, 57382, 57276, 57165, 69124], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Food10Add = 55` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/ItemDamageModifiers.cs:33`.
pub static D55_0: DamageModifierDef = DamageModifierDef {
    id: 55,
    name: "Food: -10%",
    icon: "https://render.guildwars2.com/file/779D3F0ABE5B46C09CFC57374DA8CC3A495F291C/436367.png",
    description: "-10% Additive",
    source: ModSource::Item,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[39302, 39348, 39341, 33574, 33148, 33476, 39500, 39067, 39344, 39042, 33337, 58512], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (8).
pub static DEFS: &[&DamageModifierDef] = &[
    &D10_0,
    &D51_0,
    &D211_0,
    &D212_0,
    &D52_0,
    &D53_0,
    &D54_0,
    &D55_0,
];
