//! `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs` -- the Luminary definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_RadiantArmamentsHammer = 374` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:59`.
pub static D374_0: DamageModifierDef = DamageModifierDef {
    id: 374,
    name: "Radiant Armaments (Hammer)",
    icon: "https://render.guildwars2.com/file/37424E9DD0A3ADC61DD56BB180C96201DB61099C/3679960.png",
    description: "10%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77207, 77360], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: 192224,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RadiantArmamentsHammer = 374` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:61`.
pub static D374_1: DamageModifierDef = DamageModifierDef {
    id: 374,
    name: "Radiant Armaments (Hammer)",
    icon: "https://render.guildwars2.com/file/37424E9DD0A3ADC61DD56BB180C96201DB61099C/3679960.png",
    description: "10%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77207, 77360], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 192224,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RadiantArmamentsHammer = 374` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:63`.
pub static D374_2: DamageModifierDef = DamageModifierDef {
    id: 374,
    name: "Radiant Armaments (Hammer)",
    icon: "https://render.guildwars2.com/file/37424E9DD0A3ADC61DD56BB180C96201DB61099C/3679960.png",
    description: "7%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77207, 77360], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 192224,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessing = 368` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:73`.
pub static D368_0: DamageModifierDef = DamageModifierDef {
    id: 368,
    name: "Luminary's Blessing",
    icon: "https://render.guildwars2.com/file/6C920751304B14ADFFB6A70CACEA1B80D2ABFC59/3679965.png",
    description: "-10%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: true,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessing = 368` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:76`.
pub static D368_1: DamageModifierDef = DamageModifierDef {
    id: 368,
    name: "Luminary's Blessing",
    icon: "https://render.guildwars2.com/file/6C920751304B14ADFFB6A70CACEA1B80D2ABFC59/3679965.png",
    description: "-10%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: true,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessing = 368` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:79`.
pub static D368_2: DamageModifierDef = DamageModifierDef {
    id: 368,
    name: "Luminary's Blessing",
    icon: "https://render.guildwars2.com/file/6C920751304B14ADFFB6A70CACEA1B80D2ABFC59/3679965.png",
    description: "-7%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: true,
    gain_per_stack: -7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: 193778,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessing = 368` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:82`.
pub static D368_3: DamageModifierDef = DamageModifierDef {
    id: 368,
    name: "Luminary's Blessing",
    icon: "https://render.guildwars2.com/file/6C920751304B14ADFFB6A70CACEA1B80D2ABFC59/3679965.png",
    description: "-5%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: true,
    gain_per_stack: -5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: 193778,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessing = 368` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:85`.
pub static D368_4: DamageModifierDef = DamageModifierDef {
    id: 368,
    name: "Luminary's Blessing",
    icon: "https://render.guildwars2.com/file/6C920751304B14ADFFB6A70CACEA1B80D2ABFC59/3679965.png",
    description: "-5%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: true,
    gain_per_stack: -5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 193778,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessingResoluteBlessing = 390` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:89`.
pub static D390_0: DamageModifierDef = DamageModifierDef {
    id: 390,
    name: "Resolute Blessing",
    icon: "https://render.guildwars2.com/file/3580BB0C4F3E9BBC96080454BE9491CC934A6C55/3679956.png",
    description: "-10% under Luminary's Blessing while traited",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LuminarysBlessingResoluteBlessing = 390` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:91`.
pub static D390_1: DamageModifierDef = DamageModifierDef {
    id: 390,
    name: "Resolute Blessing",
    icon: "https://render.guildwars2.com/file/3580BB0C4F3E9BBC96080454BE9491CC934A6C55/3679956.png",
    description: "-7% under Luminary's Blessing while traited",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: false,
    gain_per_stack: -7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77333], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_RadiantArmamentsShieldLingering = 376` -- `GW2EIEvtcParser/EIData/ProfHelpers/Guardian/LuminaryHelper.cs:96`.
pub static D376_0: DamageModifierDef = DamageModifierDef {
    id: 376,
    name: "Radiant Armaments (Shield Lingering)",
    icon: "https://render.guildwars2.com/file/06735858B4DE086359A7DB1D4B2B650F97D7DD03/3680144.png",
    description: "-10%",
    source: ModSource::Spec("Luminary"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77360], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (11).
pub static DEFS: &[&DamageModifierDef] = &[
    &D374_0,
    &D374_1,
    &D374_2,
    &D368_0,
    &D368_1,
    &D368_2,
    &D368_3,
    &D368_4,
    &D390_0,
    &D390_1,
    &D376_0,
];
