//! `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs` -- the Necromancer definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_CloseToDeath = 21` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:99`.
pub static D21_0: DamageModifierDef = DamageModifierDef {
    id: 21,
    name: "Close to Death",
    icon: "https://render.guildwars2.com/file/ADD8DB0EA734C99FE123FF0A513E0D124FD4AC2E/1012601.png",
    description: "20% below 50% HP",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::AgainstUnderFifty],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_SoulBarbs = 124` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:103`.
pub static D124_0: DamageModifierDef = DamageModifierDef {
    id: 124,
    name: "Soul Barbs",
    icon: "https://render.guildwars2.com/file/59A0DA7819F43F1B5E689B14CE0D0ABCC0EF3173/1012585.png",
    description: "10% after entering or exiting shroud",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[53489], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 94051,
    max_gw2_build: 115190,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_SoulBarbs = 124` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:105`.
pub static D124_1: DamageModifierDef = DamageModifierDef {
    id: 124,
    name: "Soul Barbs",
    icon: "https://render.guildwars2.com/file/59A0DA7819F43F1B5E689B14CE0D0ABCC0EF3173/1012585.png",
    description: "10% after entering or exiting shroud",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[53489], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndConditionAndLifeLeech,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 115190,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DeathPerception = 125` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:108`.
pub static D125_0: DamageModifierDef = DamageModifierDef {
    id: 125,
    name: "Death Perception",
    icon: "https://render.guildwars2.com/file/D2360AB8930CAA809136287E6DA03DA37360E1A7/1012589.png",
    description: "15% crit damage while in shroud",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[790, 29446, 40052, 59964, 76958], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Crit],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 130910,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DeathPerception = 125` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:111`.
pub static D125_1: DamageModifierDef = DamageModifierDef {
    id: 125,
    name: "Death Perception",
    icon: "https://render.guildwars2.com/file/D2360AB8930CAA809136287E6DA03DA37360E1A7/1012589.png",
    description: "15% crit damage while in shroud",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[790, 29446, 40052, 59964, 76958], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Crit],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DeathPerception = 125` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:114`.
pub static D125_2: DamageModifierDef = DamageModifierDef {
    id: 125,
    name: "Death Perception",
    icon: "https://render.guildwars2.com/file/D2360AB8930CAA809136287E6DA03DA37360E1A7/1012589.png",
    description: "10% crit damage while in shroud",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[790, 29446, 40052, 59964, 76958], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Crit],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DeathShroud = 126` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:127`.
pub static D126_0: DamageModifierDef = DamageModifierDef {
    id: 126,
    name: "Death Shroud",
    icon: "https://render.guildwars2.com/file/01B603B6CE41416CD0582AAC1D3A33DE3E086BFA/103298.png",
    description: "-33%",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: -33.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[790], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DeathShroud = 126` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:128`.
pub static D126_1: DamageModifierDef = DamageModifierDef {
    id: 126,
    name: "Death Shroud",
    icon: "https://render.guildwars2.com/file/01B603B6CE41416CD0582AAC1D3A33DE3E086BFA/103298.png",
    description: "-50%",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: -50.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[790], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DarkDefiance = 336` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:132`.
pub static D336_0: DamageModifierDef = DamageModifierDef {
    id: 336,
    name: "Dark Defiance",
    icon: "https://render.guildwars2.com/file/07E34F107B380DFDEFAF1894C66973BCFC3B3D9D/1012562.png",
    description: "-20%",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: -20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[717], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 94051,
    max_gw2_build: 203989,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DarkDefiance = 336` -- `GW2EIEvtcParser/EIData/ProfHelpers/Necromancer/NecromancerHelper.cs:134`.
pub static D336_1: DamageModifierDef = DamageModifierDef {
    id: 336,
    name: "Dark Defense",
    icon: "https://render.guildwars2.com/file/07E34F107B380DFDEFAF1894C66973BCFC3B3D9D/1012562.png",
    description: "-20%",
    source: ModSource::Spec("Necromancer"),
    spec_specific_shared: false,
    gain_per_stack: -20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[717], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 203989,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (10).
pub static DEFS: &[&DamageModifierDef] = &[
    &D21_0,
    &D124_0,
    &D124_1,
    &D125_0,
    &D125_1,
    &D125_2,
    &D126_0,
    &D126_1,
    &D336_0,
    &D336_1,
];
