//! `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs` -- the Paragon definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:20`.
pub static D369_0: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "20%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:22`.
pub static D369_1: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "15%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:25`.
pub static D369_2: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "15%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:27`.
pub static D369_3: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "10%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: 194969,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:29`.
pub static D369_4: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "10%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 194969,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:31`.
pub static D369_5: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "7%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 194969,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfAction_StrengtheningStanzas = 369` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:33`.
pub static D369_6: DamageModifierDef = DamageModifierDef {
    id: 369,
    name: "Strengthening Stanzas: Chant of Action",
    icon: "https://render.guildwars2.com/file/A4D0D740CF360E0840EF76282843109C759C63A8/3680225.png",
    description: "10%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76865], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfRecuperation_StrengtheningStanzas = 370` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:70`.
pub static D370_0: DamageModifierDef = DamageModifierDef {
    id: 370,
    name: "Strengthening Stanzas: Chant of Recuperation",
    icon: "https://render.guildwars2.com/file/2D4B0C67FACAADD8612746BD6F5C6BE9A828C9A3/3680227.png",
    description: "-20%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: -20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77378], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfRecuperation_StrengtheningStanzas = 370` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:72`.
pub static D370_1: DamageModifierDef = DamageModifierDef {
    id: 370,
    name: "Strengthening Stanzas: Chant of Recuperation",
    icon: "https://render.guildwars2.com/file/2D4B0C67FACAADD8612746BD6F5C6BE9A828C9A3/3680227.png",
    description: "-15%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: -15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77378], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfRecuperation_StrengtheningStanzas = 370` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:75`.
pub static D370_2: DamageModifierDef = DamageModifierDef {
    id: 370,
    name: "Strengthening Stanzas: Chant of Recuperation",
    icon: "https://render.guildwars2.com/file/2D4B0C67FACAADD8612746BD6F5C6BE9A828C9A3/3680227.png",
    description: "-15%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: -15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77378], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ChantOfRecuperation_StrengtheningStanzas = 370` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/ParagonHelper.cs:77`.
pub static D370_3: DamageModifierDef = DamageModifierDef {
    id: 370,
    name: "Strengthening Stanzas: Chant of Recuperation",
    icon: "https://render.guildwars2.com/file/2D4B0C67FACAADD8612746BD6F5C6BE9A828C9A3/3680227.png",
    description: "-7%",
    source: ModSource::Spec("Paragon"),
    spec_specific_shared: false,
    gain_per_stack: -7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77378], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (11).
pub static DEFS: &[&DamageModifierDef] = &[
    &D369_0,
    &D369_1,
    &D369_2,
    &D369_3,
    &D369_4,
    &D369_5,
    &D369_6,
    &D370_0,
    &D370_1,
    &D370_2,
    &D370_3,
];
