//! `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs` -- the Ranger definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_HuntersTactics = 25` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:474`.
pub static D25_0: DamageModifierDef = DamageModifierDef {
    id: 25,
    name: "Hunter's Tactics",
    icon: "https://render.guildwars2.com/file/44D4631FB427F09BE5B300BE0F537E6F2126BA0B/1012653.png",
    description: "10% while flanking",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Flanking],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 102321,
    max_gw2_build: 130910,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_HuntersTactics = 25` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:476`.
pub static D25_1: DamageModifierDef = DamageModifierDef {
    id: 25,
    name: "Hunter's Tactics",
    icon: "https://render.guildwars2.com/file/44D4631FB427F09BE5B300BE0F537E6F2126BA0B/1012653.png",
    description: "10% while flanking",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Flanking],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 130910,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_HuntersTactics = 25` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:478`.
pub static D25_2: DamageModifierDef = DamageModifierDef {
    id: 25,
    name: "Hunter's Tactics",
    icon: "https://render.guildwars2.com/file/44D4631FB427F09BE5B300BE0F537E6F2126BA0B/1012653.png",
    description: "15% while flanking",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::Flanking],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 130910,
    max_gw2_build: 147734,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BountifulHunterWithPet = 334` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:489`.
pub static D334_0: DamageModifierDef = DamageModifierDef {
    id: 334,
    name: "Bountiful Hunter",
    icon: "https://render.guildwars2.com/file/03559445FF973DE04DAB39FB64DE0D96063409E2/1012630.png",
    description: "1% per boon (player and pet)",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740, 725, 1187, 30328, 717, 718, 726, 743, 1122, 719, 26980, 873], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::All,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForceOfNature = 131` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:535`.
pub static D131_0: DamageModifierDef = DamageModifierDef {
    id: 131,
    name: "Force of Nature",
    icon: "https://render.guildwars2.com/file/4016A1FF035FC6F8A95809B5ABDAF50A92BC029B/3256318.png",
    description: "25%",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[12579], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 158837,
    max_gw2_build: 159951,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForceOfNature = 131` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:537`.
pub static D131_1: DamageModifierDef = DamageModifierDef {
    id: 131,
    name: "Force of Nature",
    icon: "https://render.guildwars2.com/file/4016A1FF035FC6F8A95809B5ABDAF50A92BC029B/3256318.png",
    description: "15%",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[12579], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 159951,
    max_gw2_build: 163141,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForceOfNature = 131` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:539`.
pub static D131_2: DamageModifierDef = DamageModifierDef {
    id: 131,
    name: "Force of Nature",
    icon: "https://render.guildwars2.com/file/4016A1FF035FC6F8A95809B5ABDAF50A92BC029B/3256318.png",
    description: "10%",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[12579], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 159951,
    max_gw2_build: 163141,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForceOfNature = 131` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:541`.
pub static D131_3: DamageModifierDef = DamageModifierDef {
    id: 131,
    name: "Force of Nature",
    icon: "https://render.guildwars2.com/file/4016A1FF035FC6F8A95809B5ABDAF50A92BC029B/3256318.png",
    description: "10%",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[12579], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 163141,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_OakheartSalve = 132` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/RangerHelper.cs:549`.
pub static D132_0: DamageModifierDef = DamageModifierDef {
    id: 132,
    name: "Oakheart Salve",
    icon: "https://render.guildwars2.com/file/4ED02272F05D430FECBB55DBAEBE2B3F776F3E1C/1012657.png",
    description: "-5% under regeneration",
    source: ModSource::Spec("Ranger"),
    spec_specific_shared: false,
    gain_per_stack: -5.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[718], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (9).
pub static DEFS: &[&DamageModifierDef] = &[
    &D25_0,
    &D25_1,
    &D25_2,
    &D334_0,
    &D131_0,
    &D131_1,
    &D131_2,
    &D131_3,
    &D132_0,
];
