//! Profession-agnostic shared modifiers (`SharedDamageModifiers.cs`) -- boons, conditions and the Exposed family.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_MightEqual25 = 422` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:36`.
pub static D422_0: DamageModifierDef = DamageModifierDef {
    id: 422,
    name: "Might 25",
    icon: "https://i.imgur.com/aXVbVl6.png",
    description: "With 25 stacks of Might",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::ExactNStacks(25),
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::StrikeAndCondition,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_MightAbove20 = 423` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:37`.
pub static D423_0: DamageModifierDef = DamageModifierDef {
    id: 423,
    name: "Might >= 20",
    icon: "https://i.imgur.com/HbDL75f.png",
    description: "With at least 20 stacks of Might",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::AtLeastNStacks(20),
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::StrikeAndCondition,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_MightLess15 = 424` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:38`.
pub static D424_0: DamageModifierDef = DamageModifierDef {
    id: 424,
    name: "Might <= 15",
    icon: "https://i.imgur.com/IimHVxe.png",
    description: "With less than 15 stacks of Might",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::AtMostNStacks(15),
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::StrikeAndCondition,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Fury = 429` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:39`.
pub static D429_0: DamageModifierDef = DamageModifierDef {
    id: 429,
    name: "Fury",
    icon: "https://render.guildwars2.com/file/96D90DF84CAFE008233DD1C2606A12C1A0E68048/102842.png",
    description: "Under Fury",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[725], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::Strike,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Emboldened = 56` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:59`.
pub static D56_0: DamageModifierDef = DamageModifierDef {
    id: 56,
    name: "Emboldened",
    icon: "https://wiki.guildwars2.com/images/6/69/Emboldened.png",
    description: "10% per stack",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[68087], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 130910,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StabilityAbove10 = 428` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:66`.
pub static D428_0: DamageModifierDef = DamageModifierDef {
    id: 428,
    name: "Stability >= 10",
    icon: "https://i.imgur.com/nAaynHA.png",
    description: "With at least 10 stacks of Stability",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::AtLeastNStacks(10),
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::All,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StabilityAbove5 = 427` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:67`.
pub static D427_0: DamageModifierDef = DamageModifierDef {
    id: 427,
    name: "Stability >= 5",
    icon: "https://i.imgur.com/Z4YUAvW.png",
    description: "With at least 5 stacks of Stability",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::AtLeastNStacks(5),
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::All,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StabilityAbove3 = 426` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:68`.
pub static D426_0: DamageModifierDef = DamageModifierDef {
    id: 426,
    name: "Stability >= 3",
    icon: "https://i.imgur.com/byOtZxM.png",
    description: "With at least 3 stacks of Stability",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::AtLeastNStacks(3),
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::All,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StabilityAbove1 = 425` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:69`.
pub static D425_0: DamageModifierDef = DamageModifierDef {
    id: 425,
    name: "Stability >= 1",
    icon: "https://i.imgur.com/ArLGcWu.png",
    description: "With at least 1 stack of Stability",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 100.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::All,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: true,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Protection = 58` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:70`.
pub static D58_0: DamageModifierDef = DamageModifierDef {
    id: 58,
    name: "Protection",
    icon: "https://render.guildwars2.com/file/CD77D1FAB7B270223538A8F8ECDA1CFB044D65F4/102834.png",
    description: "-33%",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: -33.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[717], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Resolution = 59` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:71`.
pub static D59_0: DamageModifierDef = DamageModifierDef {
    id: 59,
    name: "Resolution",
    icon: "https://render.guildwars2.com/file/D104A6B9344A2E2096424A3C300E46BC2926E4D7/2440718.png",
    description: "-33%",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: -33.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Vulnerability = 57` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:73`.
pub static D57_0: DamageModifierDef = DamageModifierDef {
    id: 57,
    name: "Vulnerability",
    icon: "https://render.guildwars2.com/file/3A394C1A0A3257EB27A44842DDEEF0DF000E1241/102850.png",
    description: "1% per Stack",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[738], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[HitCheck::DstLacksBuff(26980)],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_FrostAura = 60` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:75`.
pub static D60_0: DamageModifierDef = DamageModifierDef {
    id: 60,
    name: "Frost Aura",
    icon: "https://render.guildwars2.com/file/719B80E35C276D68EF0AABB79126CF4CD42E3AF6/2261522.png",
    description: "-10%",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[5579], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LightAura = 61` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:76`.
pub static D61_0: DamageModifierDef = DamageModifierDef {
    id: 61,
    name: "Light Aura",
    icon: "https://render.guildwars2.com/file/62405ED2322E80A4A95663BA6C6804DB0962E6B0/867451.png",
    description: "-10%",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[25518], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_DarkAura = 62` -- `GW2EIEvtcParser/EIData/DamageModifiers/CommonDamageModifiers/SharedDamageModifiers.cs:77`.
pub static D62_0: DamageModifierDef = DamageModifierDef {
    id: 62,
    name: "Dark Aura",
    icon: "https://render.guildwars2.com/file/9471B12401BB04730A0614E277FEFD6AE43C5251/2261519.png",
    description: "-20%",
    source: ModSource::Common,
    spec_specific_shared: false,
    gain_per_stack: -20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[39978], multi: false }, from_foe: false },
    src_type: DamageType::Condition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (15).
pub static DEFS: &[&DamageModifierDef] = &[
    &D422_0,
    &D423_0,
    &D424_0,
    &D429_0,
    &D56_0,
    &D428_0,
    &D427_0,
    &D426_0,
    &D425_0,
    &D58_0,
    &D59_0,
    &D57_0,
    &D60_0,
    &D61_0,
    &D62_0,
];
