//! `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs` -- the Troubadour definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_AlteredChord = 362` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:27`.
pub static D362_0: DamageModifierDef = DamageModifierDef {
    id: 362,
    name: "Altered Chord",
    icon: "https://render.guildwars2.com/file/57FB13067F3039331F0C03A63B0D07242F0C72C4/3679975.png",
    description: "25%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76759], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_AlteredChord = 362` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:28`.
pub static D362_1: DamageModifierDef = DamageModifierDef {
    id: 362,
    name: "Altered Chord",
    icon: "https://render.guildwars2.com/file/57FB13067F3039331F0C03A63B0D07242F0C72C4/3679975.png",
    description: "15%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76759], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LutePlaying = 361` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:31`.
pub static D361_0: DamageModifierDef = DamageModifierDef {
    id: 361,
    name: "Lute Playing",
    icon: "https://render.guildwars2.com/file/4CAA3750145A55B7E73D5EB9917590EC45657BE7/3680159.png",
    description: "4%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 4.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77297], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LutePlaying = 361` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:33`.
pub static D361_1: DamageModifierDef = DamageModifierDef {
    id: 361,
    name: "Lute Playing",
    icon: "https://render.guildwars2.com/file/4CAA3750145A55B7E73D5EB9917590EC45657BE7/3680159.png",
    description: "10%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77297], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Shredding = 364` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:41`.
pub static D364_0: DamageModifierDef = DamageModifierDef {
    id: 364,
    name: "Shredding",
    icon: "https://render.guildwars2.com/file/EF2D16FDF29BDCFEEC96503E0145BE1A9846F04C/3679970.png",
    description: "20%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77297], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 186019,
    max_gw2_build: 190000,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Shredding = 364` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:43`.
pub static D364_1: DamageModifierDef = DamageModifierDef {
    id: 364,
    name: "Shredding (Replaces Lute Playing)",
    icon: "https://render.guildwars2.com/file/EF2D16FDF29BDCFEEC96503E0145BE1A9846F04C/3679970.png",
    description: "25%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77297], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Shredding = 364` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:45`.
pub static D364_2: DamageModifierDef = DamageModifierDef {
    id: 364,
    name: "Shredding (Replaces Lute Playing)",
    icon: "https://render.guildwars2.com/file/EF2D16FDF29BDCFEEC96503E0145BE1A9846F04C/3679970.png",
    description: "20%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[77297], multi: false }, from_foe: false },
    src_type: DamageType::StrikeAndCondition,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LoveSong = 411` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:54`.
pub static D411_0: DamageModifierDef = DamageModifierDef {
    id: 411,
    name: "Love Song",
    icon: "https://render.guildwars2.com/file/1CC50D6BDDE64580522F0D396D194C020AC50DCE/3679972.png",
    description: "-10%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76624], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_LoveSong = 411` -- `GW2EIEvtcParser/EIData/ProfHelpers/Mesmer/TroubadourHelper.cs:56`.
pub static D411_1: DamageModifierDef = DamageModifierDef {
    id: 411,
    name: "Love Song",
    icon: "https://render.guildwars2.com/file/1CC50D6BDDE64580522F0D396D194C020AC50DCE/3679972.png",
    description: "-7%",
    source: ModSource::Spec("Troubadour"),
    spec_specific_shared: false,
    gain_per_stack: -7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[76624], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 190000,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (9).
pub static DEFS: &[&DamageModifierDef] = &[
    &D362_0,
    &D362_1,
    &D361_0,
    &D361_1,
    &D364_0,
    &D364_1,
    &D364_2,
    &D411_0,
    &D411_1,
];
