//! `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs` -- the Untamed definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:63`.
pub static D93_0: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "15% when unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 118697,
    max_gw2_build: 126520,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:65`.
pub static D93_1: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "25% when unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 126520,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:67`.
pub static D93_2: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "15% when unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 126520,
    max_gw2_build: 146069,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:69`.
pub static D93_3: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "10% when unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 146069,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:71`.
pub static D93_4: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "15% when unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 146069,
    max_gw2_build: 175086,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:73`.
pub static D93_5: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "20% when unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 175086,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:75`.
pub static D93_6: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "25% when unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:77`.
pub static D93_7: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "10% when unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 203989,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:79`.
pub static D93_8: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "20% when unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 20.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:81`.
pub static D93_9: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "15% when unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: 203989,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:83`.
pub static D93_10: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "10% when unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63317, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 203989,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForestsFortification = 94` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:93`.
pub static D94_0: DamageModifierDef = DamageModifierDef {
    id: 94,
    name: "Forest's Fortification",
    icon: "https://render.guildwars2.com/file/387423FEEF4639CFF0A4532C06CBCB5701933331/2503712.png",
    description: "-50%",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -50.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63240], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 118697,
    max_gw2_build: 178947,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForestsFortification = 94` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:95`.
pub static D94_1: DamageModifierDef = DamageModifierDef {
    id: 94,
    name: "Forest's Fortification",
    icon: "https://render.guildwars2.com/file/387423FEEF4639CFF0A4532C06CBCB5701933331/2503712.png",
    description: "-33%",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -33.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63240], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 178947,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_ForestsFortification = 94` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:97`.
pub static D94_2: DamageModifierDef = DamageModifierDef {
    id: 94,
    name: "Forest's Fortification",
    icon: "https://render.guildwars2.com/file/387423FEEF4639CFF0A4532C06CBCB5701933331/2503712.png",
    description: "-50%",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -50.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63240], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 178947,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:100`.
pub static D93_11: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-10% when not unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 118697,
    max_gw2_build: 126520,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:102`.
pub static D93_12: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-25% when not unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 126520,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:104`.
pub static D93_13: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-10% when not unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 126520,
    max_gw2_build: 175086,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:106`.
pub static D93_14: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-10% when not unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 175086,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:108`.
pub static D93_15: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-15% when not unleashed",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 175086,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:110`.
pub static D93_16: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-25% when not unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -25.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:112`.
pub static D93_17: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-10% when not unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 203989,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:114`.
pub static D93_18: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-15% when not unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -15.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::WvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 203989,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_VowOfTheUntamed = 93` -- `GW2EIEvtcParser/EIData/ProfHelpers/Ranger/UntamedHelper.cs:116`.
pub static D93_19: DamageModifierDef = DamageModifierDef {
    id: 93,
    name: "Vow of the Untamed",
    icon: "https://render.guildwars2.com/file/6C71F5D550E3CBACBB067376F52DE40A0148776F/2503643.png",
    description: "-10% when not unleashed or biorhythm proc",
    source: ModSource::Spec("Untamed"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[63145, 76502], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 203989,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (23).
pub static DEFS: &[&DamageModifierDef] = &[
    &D93_0,
    &D93_1,
    &D93_2,
    &D93_3,
    &D93_4,
    &D93_5,
    &D93_6,
    &D93_7,
    &D93_8,
    &D93_9,
    &D93_10,
    &D94_0,
    &D94_1,
    &D94_2,
    &D93_11,
    &D93_12,
    &D93_13,
    &D93_14,
    &D93_15,
    &D93_16,
    &D93_17,
    &D93_18,
    &D93_19,
];
