//! `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs` -- the Warrior definitions observed in the WvW reference capture.
//!
//! Machine-transcribed from GW2EI; every entry carries the `file:line` of
//! the C# statement it came from. See `super`'s module doc for the
//! transcription rules and the skipped-definition list.

#![allow(clippy::excessive_precision)]

use super::super::model::*;

/// GW2EI `Mod_BerserkersPower = 172` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:72`.
pub static D172_0: DamageModifierDef = DamageModifierDef {
    id: 172,
    name: "Berserker's Power",
    icon: "https://render.guildwars2.com/file/A795EE78B8DAA836F3C0650CFC037BB71D3517BA/1012816.png",
    description: "7% per stack",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[42539], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: 135242,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BerserkersPower = 172` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:74`.
pub static D172_1: DamageModifierDef = DamageModifierDef {
    id: 172,
    name: "Berserker's Power",
    icon: "https://render.guildwars2.com/file/A795EE78B8DAA836F3C0650CFC037BB71D3517BA/1012816.png",
    description: "5.25% per stack",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 5.25,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[42539], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 135242,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BerserkersPower = 172` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:76`.
pub static D172_2: DamageModifierDef = DamageModifierDef {
    id: 172,
    name: "Berserker's Power",
    icon: "https://render.guildwars2.com/file/A795EE78B8DAA836F3C0650CFC037BB71D3517BA/1012816.png",
    description: "5.25% per stack",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 5.25,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[42539], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_BerserkersPower = 172` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:78`.
pub static D172_3: DamageModifierDef = DamageModifierDef {
    id: 172,
    name: "Berserker's Power",
    icon: "https://render.guildwars2.com/file/A795EE78B8DAA836F3C0650CFC037BB71D3517BA/1012816.png",
    description: "3.75% per stack",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 3.75,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[42539], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StalwartStrength = 173` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:83`.
pub static D173_0: DamageModifierDef = DamageModifierDef {
    id: 173,
    name: "Stalwart Strength",
    icon: "https://render.guildwars2.com/file/630279C914D8BF414C2358281F1A37EDF86B203B/1012794.png",
    description: "10%",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 135242,
    max_gw2_build: 182824,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StalwartStrength = 173` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:85`.
pub static D173_1: DamageModifierDef = DamageModifierDef {
    id: 173,
    name: "Stalwart Strength",
    icon: "https://render.guildwars2.com/file/630279C914D8BF414C2358281F1A37EDF86B203B/1012794.png",
    description: "12.5%",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 12.5,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StalwartStrength = 173` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:87`.
pub static D173_2: DamageModifierDef = DamageModifierDef {
    id: 173,
    name: "Stalwart Strength",
    icon: "https://render.guildwars2.com/file/630279C914D8BF414C2358281F1A37EDF86B203B/1012794.png",
    description: "10%",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 182824,
    max_gw2_build: 198816,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_StalwartStrength = 173` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:89`.
pub static D173_3: DamageModifierDef = DamageModifierDef {
    id: 173,
    name: "Stalwart Strength",
    icon: "https://render.guildwars2.com/file/630279C914D8BF414C2358281F1A37EDF86B203B/1012794.png",
    description: "10%",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[1122], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 198816,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_Empowered = 174` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:121`.
pub static D174_0: DamageModifierDef = DamageModifierDef {
    id: 174,
    name: "Empowered",
    icon: "https://render.guildwars2.com/file/B4361E2EC6AE0C58977573C7C6F6F6FD12032FA7/2207778.png",
    description: "1% per boon",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 1.0,
    gain: GainComputer::ByStack,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[740, 725, 1187, 30328, 717, 718, 726, 743, 1122, 719, 26980, 873], multi: true }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: START_OF_LIFE,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsCunningBarrier = 36` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:123`.
pub static D36_0: DamageModifierDef = DamageModifierDef {
    id: 36,
    name: "Warrior's Cunning (Barrier)",
    icon: "https://render.guildwars2.com/file/0848D11E545D0B62601FAD03DE6D4A37E2EC4E9A/2207776.png",
    description: "50% against barrier",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 50.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::ShieldDamage],
    mode: ModifierMode::PvEWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 100690,
    max_gw2_build: 147734,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsCunningBarrier = 36` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:125`.
pub static D36_1: DamageModifierDef = DamageModifierDef {
    id: 36,
    name: "Warrior's Cunning (Barrier)",
    icon: "https://render.guildwars2.com/file/0848D11E545D0B62601FAD03DE6D4A37E2EC4E9A/2207776.png",
    description: "50% against barrier",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 50.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::ShieldDamage],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 147734,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsCunningBarrier = 36` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:127`.
pub static D36_2: DamageModifierDef = DamageModifierDef {
    id: 36,
    name: "Warrior's Cunning (Barrier)",
    icon: "https://render.guildwars2.com/file/0848D11E545D0B62601FAD03DE6D4A37E2EC4E9A/2207776.png",
    description: "10% against barrier",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::ShieldDamage],
    mode: ModifierMode::SPvP,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 100690,
    max_gw2_build: 147734,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsCunningBarrier = 36` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:129`.
pub static D36_3: DamageModifierDef = DamageModifierDef {
    id: 36,
    name: "Warrior's Cunning (Barrier)",
    icon: "https://render.guildwars2.com/file/0848D11E545D0B62601FAD03DE6D4A37E2EC4E9A/2207776.png",
    description: "10% against barrier",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::Hit,
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[HitCheck::ShieldDamage],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 147734,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsSprint = 175` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:153`.
pub static D175_0: DamageModifierDef = DamageModifierDef {
    id: 175,
    name: "Warrior's Sprint",
    icon: "https://render.guildwars2.com/file/0D0DD0E0002F5ED423FF01A85E9890D32CE7960E/1012799.png",
    description: "7% under swiftness",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 7.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[719], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 86181,
    max_gw2_build: 115190,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsSprint = 175` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:155`.
pub static D175_1: DamageModifierDef = DamageModifierDef {
    id: 175,
    name: "Warrior's Sprint",
    icon: "https://render.guildwars2.com/file/0D0DD0E0002F5ED423FF01A85E9890D32CE7960E/1012799.png",
    description: "3% under swiftness",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 3.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[719], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::SPvPWvW,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 86181,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_WarriorsSprint = 175` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:157`.
pub static D175_2: DamageModifierDef = DamageModifierDef {
    id: 175,
    name: "Warrior's Sprint",
    icon: "https://render.guildwars2.com/file/0D0DD0E0002F5ED423FF01A85E9890D32CE7960E/1012799.png",
    description: "10% under swiftness",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: 10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[719], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::NoPets,
    checks: &[],
    mode: ModifierMode::PvE,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 115190,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_HardenedArmor = 176` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:180`.
pub static D176_0: DamageModifierDef = DamageModifierDef {
    id: 176,
    name: "Hardened Armor",
    icon: "https://render.guildwars2.com/file/10055830259435E5B2B1B2EC1E63FCDC9648CC4D/1012797.png",
    description: "-10% under retaliation",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 102724,
    max_gw2_build: 115190,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// GW2EI `Mod_HardenedArmor = 176` -- `GW2EIEvtcParser/EIData/ProfHelpers/Warrior/WarriorHelper.cs:182`.
pub static D176_1: DamageModifierDef = DamageModifierDef {
    id: 176,
    name: "Hardened Armor",
    icon: "https://render.guildwars2.com/file/10055830259435E5B2B1B2EC1E63FCDC9648CC4D/1012797.png",
    description: "-10% under resolution",
    source: ModSource::Spec("Warrior"),
    spec_specific_shared: false,
    gain_per_stack: -10.0,
    gain: GainComputer::ByPresence,
    trigger: Trigger::BuffOnActor { tracker: BuffTracker { ids: &[873], multi: false }, from_foe: false },
    src_type: DamageType::Strike,
    compare_type: DamageType::All,
    dmg_src: DamageSource::Incoming,
    checks: &[],
    mode: ModifierMode::All,
    approximate: false,
    is_counter: false,
    actor_always_master: false,
    foe_always_master: false,
    with_absorbed_damage_events: false,
    min_gw2_build: 115190,
    max_gw2_build: END_OF_LIFE,
    min_evtc_build: EVTC_START_OF_LIFE,
    max_evtc_build: EVTC_END_OF_LIFE,
};

/// Every definition in this group (18).
pub static DEFS: &[&DamageModifierDef] = &[
    &D172_0,
    &D172_1,
    &D172_2,
    &D172_3,
    &D173_0,
    &D173_1,
    &D173_2,
    &D173_3,
    &D174_0,
    &D36_0,
    &D36_1,
    &D36_2,
    &D36_3,
    &D175_0,
    &D175_1,
    &D175_2,
    &D176_0,
    &D176_1,
];
