//! Squad marker and commander tag identities, from the GW2EI C# sources.
//!
//! GENERATED by `scripts/gen_marker_catalog.py` -- do not hand-edit. Re-run
//! it and `git diff` to verify this table against GW2EI's source.
//!
//! arcdps reports a marker as a raw 32-hex-character content GUID and
//! nothing else -- not its colour, not whether it is a tag or an arrow, and
//! no art. This table answers all three, from `MarkerGUIDs` (identity) plus
//! `ParserIcons.SquadMarkerToIcon` and `ParserIcons.CommanderTagToIcon`
//! (art).
//!
//! GUIDs are stored LOWERCASE, matching what axilog emits in
//! `encounter.markers[].marker`. GW2EI writes them uppercase, and a case
//! mismatch would make every lookup miss silently rather than loudly.
//!
//! The generator's accounting for this table:
//!
//! considered 26 = transcribed 26 + skipped 0
//!
//! Of the 26 transcribed, 26 carry art and 0 are
//! named only -- GW2EI names more marker GUIDs than it supplies icons for,
//! and a name alone still beats showing a hex string.
//!
//! - (none)
//!
//! Entries are sorted by GUID so lookups can binary-search.

/// One marker identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Marker {
    /// Lowercase 32-hex content GUID, as `encounter.markers[].marker` spells it.
    pub guid: &'static str,
    /// `"squad_marker"`, `"commander_tag"` or `"catmander_tag"`.
    pub kind: &'static str,
    /// `"Arrow"`, `"Purple"`, `"X"` -- the symbol name minus its kind suffix.
    pub label: &'static str,
    /// Wiki art, when GW2EI supplies any for this GUID.
    pub icon: Option<&'static str>,
}

/// The marker `guid` names, or `None` when GW2EI does not know it.
///
/// Matching is case-sensitive against the lowercase spelling; callers
/// holding an uppercase GUID must lowercase it first.
pub fn lookup(guid: &str) -> Option<&'static Marker> {
    MARKERS
        .binary_search_by_key(&guid, |m| m.guid)
        .ok()
        .map(|i| &MARKERS[i])
}

/// Every marker identity GW2EI declares, sorted by GUID.
pub const MARKERS: &[Marker] = &[
    Marker { guid: "185008e2437b184d8fdad647dd972d9f", kind: "squad_marker", label: "Heart", icon: Some("https://wiki.guildwars2.com/images/3/32/Commander_heart_marker.png") },
    Marker { guid: "1993fadb6fb70e4383a223a54d311f7d", kind: "commander_tag", label: "Purple", icon: Some("https://wiki.guildwars2.com/images/c/cb/Commander_tag_%28purple%29.png") },
    Marker { guid: "2ca226e07262c743ba193acf6f9d0af6", kind: "catmander_tag", label: "Green", icon: Some("https://wiki.guildwars2.com/images/f/fd/Catmander_tag_%28green%29.png") },
    Marker { guid: "4242f370667ce54eb3bf22be8d06f986", kind: "commander_tag", label: "Red", icon: Some("https://wiki.guildwars2.com/images/4/40/Commander_tag_%28red%29.png") },
    Marker { guid: "4387be6146d43246aa7b333168ea58ea", kind: "catmander_tag", label: "Pink", icon: Some("https://wiki.guildwars2.com/images/9/94/Catmander_tag_%28magenta%29.png") },
    Marker { guid: "46ebc4397f8a3740b900333b591f6183", kind: "squad_marker", label: "Triangle", icon: Some("https://wiki.guildwars2.com/images/e/ea/Commander_triangle_marker.png") },
    Marker { guid: "5140125657c6084d94226c8ec0216649", kind: "squad_marker", label: "Star", icon: Some("https://wiki.guildwars2.com/images/3/31/Commander_star_marker.png") },
    Marker { guid: "6bce90e99016b448969eb317784a8334", kind: "catmander_tag", label: "Yellow", icon: Some("https://wiki.guildwars2.com/images/a/a3/Catmander_tag_%28yellow%29.png") },
    Marker { guid: "6e5997457b3f6a45b984c613806fa72a", kind: "squad_marker", label: "Square", icon: Some("https://wiki.guildwars2.com/images/0/01/Commander_square_marker.png") },
    Marker { guid: "7224a4af710e4243bfe032629e17ca6e", kind: "catmander_tag", label: "Purple", icon: Some("https://wiki.guildwars2.com/images/f/ff/Catmander_tag_%28purple%29.png") },
    Marker { guid: "73c880ae431c9f4d8a5972acf7066f4e", kind: "squad_marker", label: "Circle", icon: Some("https://wiki.guildwars2.com/images/6/60/Commander_circle_marker.png") },
    Marker { guid: "74ad480e531f4740a407879976c8ca91", kind: "commander_tag", label: "Green", icon: Some("https://wiki.guildwars2.com/images/5/5e/Commander_tag_%28green%29.png") },
    Marker { guid: "8bdcf5c47f8a8340a251f102af3b5905", kind: "squad_marker", label: "X", icon: Some("https://wiki.guildwars2.com/images/b/b9/Commander_x_marker.png") },
    Marker { guid: "96f4ab5cdec5294388375c7a03ab7614", kind: "commander_tag", label: "Cyan", icon: Some("https://wiki.guildwars2.com/images/2/2b/Commander_tag_%28cyan%29.png") },
    Marker { guid: "9b94f0fd616e7f4aa58efdc8c59fb689", kind: "catmander_tag", label: "Blue", icon: Some("https://wiki.guildwars2.com/images/1/16/Catmander_tag_%28blue%29.png") },
    Marker { guid: "9fdf03e9ba09a2458c1edda4d81bc34d", kind: "catmander_tag", label: "Orange", icon: Some("https://wiki.guildwars2.com/images/2/2a/Catmander_tag_%28orange%29.png") },
    Marker { guid: "a0b0ec076bc83b40a293c1cdec4a7de7", kind: "catmander_tag", label: "White", icon: Some("https://wiki.guildwars2.com/images/5/51/Catmander_tag_%28white%29.png") },
    Marker { guid: "a59678cdfb5732439d7fcbf58d8bcec3", kind: "commander_tag", label: "White", icon: Some("https://wiki.guildwars2.com/images/f/f1/Commander_tag_%28white%29.png") },
    Marker { guid: "a8072d65ce35924babbac831b12019d7", kind: "catmander_tag", label: "Cyan", icon: Some("https://wiki.guildwars2.com/images/9/9d/Catmander_tag_%28cyan%29.png") },
    Marker { guid: "ae714fc5e4ea464c8961cd78e86f9291", kind: "commander_tag", label: "Blue", icon: Some("https://wiki.guildwars2.com/images/5/54/Commander_tag_%28blue%29.png") },
    Marker { guid: "af9442a290c6214596e0b339eb3bde92", kind: "commander_tag", label: "Yellow", icon: Some("https://wiki.guildwars2.com/images/c/cb/Commander_tag_%28yellow%29.png") },
    Marker { guid: "c3a56f1e045e3848b07cbac5bbdd2c32", kind: "squad_marker", label: "Arrow", icon: Some("https://wiki.guildwars2.com/images/e/ef/Commander_arrow_marker.png") },
    Marker { guid: "ca76ab023593b0448f692fe29df03d17", kind: "catmander_tag", label: "Red", icon: Some("https://wiki.guildwars2.com/images/5/59/Catmander_tag_%28red%29.png") },
    Marker { guid: "e57aae9ee7fc5d458b0cf16be4b096bf", kind: "commander_tag", label: "Orange", icon: Some("https://wiki.guildwars2.com/images/1/1c/Commander_tag_%28orange%29.png") },
    Marker { guid: "e911d8c0ef2fdf4d8d252e5fb1283c62", kind: "commander_tag", label: "Pink", icon: Some("https://wiki.guildwars2.com/images/b/ba/Commander_tag_%28magenta%29.png") },
    Marker { guid: "ebbe113ae2e53f4e96f3e92fb1353ece", kind: "squad_marker", label: "Swirl", icon: Some("https://wiki.guildwars2.com/images/0/00/Commander_spiral_marker.png") },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_sorted_so_binary_search_is_valid() {
        assert!(MARKERS.windows(2).all(|w| w[0].guid < w[1].guid), "MARKERS must be sorted by guid");
    }

    /// The one marker GUID the committed WvW fixture actually carries.
    /// arcdps reports it as a bare hex string; without this table there is
    /// no way to know it means "purple commander tag".
    #[test]
    fn resolves_the_purple_commander_tag_the_fixture_carries() {
        let m = lookup("1993fadb6fb70e4383a223a54d311f7d").expect("purple commander tag");
        assert_eq!(m.kind, "commander_tag");
        assert_eq!(m.label, "Purple");
        assert!(m.icon.is_some_and(|i| i.contains("Commander_tag")), "icon: {:?}", m.icon);
    }

    /// All eight overhead squad markers resolve and carry art. The fixture
    /// has none of these, so this table is the only proof that path works.
    #[test]
    fn every_overhead_squad_marker_resolves_with_art() {
        let squad: Vec<_> = MARKERS.iter().filter(|m| m.kind == "squad_marker").collect();
        assert_eq!(squad.len(), 8, "GW2 has exactly eight overhead squad markers");
        for m in &squad {
            assert!(m.icon.is_some(), "{} has no art", m.label);
        }
        let mut labels: Vec<_> = squad.iter().map(|m| m.label).collect();
        labels.sort_unstable();
        assert_eq!(labels, ["Arrow", "Circle", "Heart", "Square", "Star", "Swirl", "Triangle", "X"]);
    }

    /// Lookups are case-sensitive by design: GW2EI writes GUIDs uppercase,
    /// the log spells them lowercase, and the caller lowercases. Pin that
    /// contract so nobody "fixes" it into a silent miss.
    #[test]
    fn lookup_is_lowercase_only() {
        assert!(lookup("1993FADB6FB70E4383A223A54D311F7D").is_none());
        assert!(lookup("1993fadb6fb70e4383a223a54d311f7d").is_some());
    }

    #[test]
    fn an_unknown_guid_resolves_to_nothing_rather_than_a_guess() {
        // Present in the committed fixture, absent from GW2EI's tables.
        assert!(lookup("3cd1c64a5000774488009d4d69455c5c").is_none());
    }
}
