//! Adrenaline-tier labels for warrior burst skills, from the official
//! GW2 API.
//!
//! GENERATED by `scripts/gen_skill_variant_catalog.py` -- do not
//! hand-edit. Re-run it and `git diff` to verify this table against the
//! live API.
//!
//! One warrior burst is five skill ids sharing ONE display name -- the
//! weapon-slot skill, the Berserker primal burst, and three adrenaline
//! tiers -- and an arcdps log names all five identically.
//! [`axilog_schema::v1`]'s `label_name_collisions` gives every id in such
//! a collision a label; this table upgrades that label from the bare id to
//! the tier, for the ids whose tier is genuinely known.
//!
//! The tier is read from the `traited_facts` entry with
//! `requires_trait == 1649` (Cleansing Ire, which cleanses one condition
//! per bar of adrenaline spent, so its `value` is the tier).
//!
//! That rule was VALIDATED against the one group with independent ground
//! truth and it FAILED. Harrier's Toss (72911 / 73042 / 73006) is carried
//! by GW2EI's `OverridenSkillNames` as Adrenaline Level 1 / 2 / 3; the
//! `requires_trait: 1649` fact returns level 1 for all five of its ids.
//! Breaching Strike behaves the same way; Path to Victory is internally
//! inconsistent; Bloodthirster has no trait facts at all.
//!
//! Those four groups are therefore NOT derived. Harrier's Toss is
//! hand-transcribed from GW2EI (the only group with an independent
//! source). The other three emit NOTHING and fall back to the id label.
//! Their absence is the correct answer, not an oversight -- do not
//! "finish the job" by re-deriving them from this rule, which is known to
//! lie on exactly this shape of input:
//!
//! - Bloodthirster: no Cleansing Ire trait fact on any id in the group
//! - Breaching Strike: the Cleansing Ire facts do not name the three distinct tiers 1/2/3, so the derivation contradicts itself
//! - Path to Victory: the Cleansing Ire facts do not name the three distinct tiers 1/2/3, so the derivation contradicts itself
//!
//! The generator's accounting:
//!
//! considered 67 = transcribed 27 + skipped 40
//!
//! - 12 weapon-slot burst skill, not an adrenaline tier
//! - 12 Berserker primal burst, not an adrenaline tier
//! - 7 not a five-id burst group (no name collision to resolve)
//! - 6 the Cleansing Ire facts do not name the three distinct tiers 1/2/3, so the derivation contradicts itself
//! - 3 no Cleansing Ire trait fact on any id in the group
//!
//! (19 burst display names in all, 9 of them labelled.)
//!
//! Entries are sorted by id so lookups can binary-search.
//!
//! The tests below are part of the generated file: they are the assertions
//! a regeneration has to keep satisfying, so they belong next to the table
//! they pin rather than somewhere a regeneration would not touch.

/// The variant label for skill `id`, or `None` when this table does not
/// cover it -- in which case the caller falls back to the id.
pub fn label(id: u32) -> Option<&'static str> {
    SKILL_VARIANT_LABELS
        .binary_search_by_key(&id, |&(sid, _)| sid)
        .ok()
        .map(|i| SKILL_VARIANT_LABELS[i].1)
}

/// `(skill id, variant label)`, sorted by id.
pub const SKILL_VARIANT_LABELS: &[(u32, &str)] = &[
    (14422, "Adrenaline 1"),
    (14423, "Adrenaline 2"),
    (14424, "Adrenaline 3"),
    (14425, "Adrenaline 1"),
    (14426, "Adrenaline 2"),
    (14427, "Adrenaline 3"),
    (14469, "Adrenaline 1"),
    (14470, "Adrenaline 2"),
    (14471, "Adrenaline 3"),
    (14473, "Adrenaline 1"),
    (14474, "Adrenaline 2"),
    (14475, "Adrenaline 3"),
    (14512, "Adrenaline 1"),
    (14513, "Adrenaline 2"),
    (14514, "Adrenaline 3"),
    (14520, "Adrenaline 1"),
    (14521, "Adrenaline 2"),
    (14522, "Adrenaline 3"),
    (14545, "Adrenaline 1"),
    (14546, "Adrenaline 2"),
    (14547, "Adrenaline 3"),
    (14549, "Adrenaline 1"),
    (14550, "Adrenaline 2"),
    (14551, "Adrenaline 3"),
    (72911, "Adrenaline 1"),
    (73006, "Adrenaline 3"),
    (73042, "Adrenaline 2"),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// The lookup binary-searches, so an unsorted table silently returns
    /// wrong answers rather than failing.
    #[test]
    fn the_table_is_sorted_and_has_no_duplicate_ids() {
        for pair in SKILL_VARIANT_LABELS.windows(2) {
            assert!(pair[0].0 < pair[1].0, "unsorted or duplicated at {:?}", pair[0]);
        }
    }

    /// Ground truth from GW2EI's OverridenSkillNames -- the ONE group with
    /// a source independent of the trait-fact derivation, and the group
    /// where that derivation was caught lying. If this breaks, the
    /// generator has started guessing again.
    #[test]
    fn harriers_toss_matches_the_gw2ei_override_table() {
        assert_eq!(label(72911), Some("Adrenaline 1"));
        assert_eq!(label(73042), Some("Adrenaline 2"));
        assert_eq!(label(73006), Some("Adrenaline 3"));
    }

    /// The group BreakN reported. Pinned so a regenerated table that
    /// reshuffles these three fails loudly instead of silently relabelling
    /// the skill players are looking at.
    #[test]
    fn earthshaker_carries_its_three_adrenaline_tiers() {
        assert_eq!(label(14512), Some("Adrenaline 1"));
        assert_eq!(label(14513), Some("Adrenaline 2"));
        assert_eq!(label(14514), Some("Adrenaline 3"));
    }

    /// The three groups the derivation could not resolve are ABSENT on
    /// purpose; they fall back to the id label. Asserting the absence
    /// stops a future edit from quietly filling them with a guess.
    ///
    /// Naming the nine ids matters more than the count does: a table that
    /// labelled Bloodthirster from ascending id order and dropped three
    /// legitimate entries elsewhere would still be 27 long.
    #[test]
    fn the_undecidable_groups_carry_no_label() {
        // Bloodthirster has no Cleansing Ire trait facts at all.
        for id in [80221, 80248, 80263] {
            assert_eq!(label(id), None, "Bloodthirster {id} must stay unlabelled");
        }
        // Breaching Strike's facts all say level 1, the same way Harrier's
        // Toss's do -- where GW2EI proves that answer wrong.
        for id in [69245, 69392, 69433] {
            assert_eq!(label(id), None, "Breaching Strike {id} must stay unlabelled");
        }
        // Path to Victory's facts are internally inconsistent.
        for id in [71922, 71950, 72029] {
            assert_eq!(label(id), None, "Path to Victory {id} must stay unlabelled");
        }

        for (id, _) in SKILL_VARIANT_LABELS {
            assert!(label(*id).is_some());
        }
        assert_eq!(SKILL_VARIANT_LABELS.len(), 27, "9 groups x 3 tiers");
    }

    #[test]
    fn an_unknown_id_has_no_label() {
        assert_eq!(label(1), None);
    }
}
