/* auto-generated by NAPI-RS */
import type { Report, ReportV1 } from './types'
/* eslint-disable */
/**
 * Rewrites every player's character/account name in the `.zevtc` at
 * `in_path` to a deterministic `Anon<N>` placeholder and writes the
 * result to `out_path` (same transform as `axilog anonymize` / the core
 * `anonymize_raw_evtc` function -- reused here, not duplicated). Returns
 * the number of player agents rewritten.
 */
export declare function anonymizeFile(inPath: string, outPath: string): number

/**
 * Parses an already-read `.evtc`/`.zevtc` buffer and returns the native
 * 1.0 container (Task 12) as a plain JS object. `opts.replay` (M9, Task 2)
 * opts into embedding the native combat-replay block; `opts.skill_damage`
 * (M12, Task 1) opts into embedding the native per-skill damage
 * distribution block; `opts.missiles` (final-review fix wave) opts into
 * embedding the native top-level missile analytics block. A buffer has no
 * file name to offer, so `generated_from` is always absent here.
 */
export declare function parseBuffer(buf: Buffer, opts?: ParseOptions | undefined | null): ReportV1

/**
 * Parses a `.evtc`/`.zevtc` file at `path` and returns the native 1.0
 * container (Task 12) as a plain JS object (see module docs for the
 * field-name behavior). `opts.replay` (M9, Task 2) opts into embedding the
 * native combat-replay block; omitted entirely for back-compat with every
 * existing zero-arg call site. Unlike `parseBuffer`, this entry point has
 * a real file name to offer, so it threads `path`'s file name (never the
 * full path) into the document's `generated_from`.
 */
export declare function parseFile(path: string, opts?: ParseOptions | undefined | null): ReportV1

/**
 * Parses a `.evtc`/`.zevtc` file at `path` and returns the Elite
 * Insights-compatibility JSON (`axilog_ei::to_ei_json`) as a plain JS
 * object. `opts` (final-review fix wave) accepts the same `ParseOptions`
 * shape `parseFile`/`parseBuffer` do -- `opts.skill_damage`/
 * `opts.timeseries` are what actually let `totalDamageDist`/`damage1S`/
 * `dpsTargets`/etc (M12, Task 3's ei-json mapping) surface in the
 * returned JSON, since `axilog_ei::to_ei_json` reads them straight off
 * the native `Report` this function builds internally; previously this
 * function always built that `Report` with both flags forced `false`,
 * silently discarding any M12 detail regardless of what a caller wanted
 * (axibridge consumes ei-json exclusively through this function).
 * As of MEIGAP2 those two flags gate three more GW2EI surfaces:
 * `opts.skill_damage` additionally carries the player distributions'
 * outcome columns (`connectedHits`/`glance`/`missed`/`evaded`/`blocked`/
 * `invulned`/`interrupted`/`indirectDamage`, plus per-skill
 * `downContribution` on the outgoing one), and `opts.timeseries`
 * additionally carries `healthPercents` and `boonsStates` -- GW2EI's own
 * `RawFormatTimelineArrays` gate on both. `instanceID`,
 * `dpsAll[0].breakbarDamage` and `targets[].dpsAll` need no flag, matching
 * GW2EI, which always emits them.
 * `opts.replay` (M15, Task 3) adds GW2EI's own combat-replay surface --
 * per-actor `combatReplayData.{positions, orientations, dc, iconURL}` plus
 * the top-level `combatReplayMetaData` (see `axilog_ei::to_ei_json`; it
 * roughly triples the payload, hence opt-in). `opts.missiles` is accepted
 * for parity with `parseFile` but has no effect on the output -- EI's JSON
 * shape has no comparable field for it. Omitting `opts`
 * entirely keeps every existing zero-arg call site's behavior unchanged.
 */
export declare function parseFileEi(path: string, opts?: ParseOptions | undefined | null): any

/**
 * Optional per-call parse settings (M9, Task 2). `replay: true` opts into
 * computing and embedding the native combat-replay block (`ReplayOut`) in
 * the returned `Report`; omitted (or `false`, or the argument itself
 * omitted entirely -- napi treats a trailing `Option<T>` parameter as
 * optional in the generated TypeScript signature) keeps the existing
 * zero-arg call shape's behavior unchanged (no `replay` key in the
 * output, matching `Report.replay`'s serde skip-when-absent).
 * `skill_damage: true` (M12, Task 1) opts into embedding the native
 * per-skill damage distribution block (`SkillDamageOut`) on every
 * `players[]` entry -- see `axilog_schema::Report::players`'s
 * `PlayerOut::skill_damage` doc comment for why this defaults to opt-in
 * (measured +249% JSON size on the committed fixture when always-on).
 * `timeseries: true` (M12, Task 2) opts into embedding the native
 * per-player per-second series block (`PlayerPerSecondOut`) AND the
 * per-enemy `dps_targets` summary on every `players[]` entry -- see
 * `axilog_schema::Report::players`'s `PlayerOut::per_second`/`PlayerOut::
 * dps_targets` doc comments (measured +147.7%/+36.4% JSON size
 * respectively on the committed fixture when always-on -- `dps_targets`
 * is NOT small on a real WvW log with many enemies, so both stay behind
 * this one flag).
 * `missiles: true` (final-review fix wave) opts into embedding the
 * native top-level missile (projectile) analytics block
 * (`Report::missiles`), mirroring the CLI's `--missiles` flag -- see
 * `axilog_core::analysis::missiles`'s module doc for exactly what it
 * contains. Omitted (or `false`) keeps `Report.missiles` absent, matching
 * its serde skip-when-`None`.
 * `rotation: true` (M14, Task 1) opts into embedding the native
 * per-player rotation (cast tracking) block (`SkillRotationOut[]`) on
 * every `players[]` entry -- see `axilog_schema::Report::players`'s
 * `PlayerOut::rotation` doc comment for why this defaults to opt-in
 * (well past the ~30% size-discipline guideline on the committed fixture
 * when always-on).
 * `modifiers: true` (M16) opts into the per-player damage-modifier stats
 * -- `players[].damage_mods.{outgoing, incoming}` plus the top-level
 * `damage_mod_map` on the native `Report` (`parseFile`/`parseBuffer`), and
 * EI's own `damageModifiers`/`incomingDamageModifiers`/
 * `damageModifiersTarget`/`incomingDamageModifiersTarget` plus
 * `damageModMap` on `parseFileEi`. Unlike every other option here this one
 * gates a COMPUTATION rather than a copy: `analyze()` never runs the
 * modifier engine, which is a separate pass over every damage event
 * crossed with ~200 catalogued definitions (see
 * `axilog_schema::DamageModsOut`'s doc comment). Off by default.
 */
export interface ParseOptions {
  replay?: boolean
  skillDamage?: boolean
  timeseries?: boolean
  missiles?: boolean
  rotation?: boolean
  modifiers?: boolean
}
