//! Trigger-id -> encounter identity, transcribed from GW2EI.
//!
//! GENERATED by `scripts/gen_encounter_catalog.py` -- do not edit by hand.
//! Tests live in `crates/axilog-core/tests/encounter_catalog.rs`, out of the
//! generator's reach.
//!
//! arcdps writes one number about the encounter into the evtc header: the
//! trigger species id (bytes 13-14, [`crate::evtc::RawHeader::boss_id`]).
//! This is the table that turns that number into "Gorseval, a Spirit Vale
//! raid wing boss" instead of the "Detailed WvW - World vs World" every PvE
//! log used to report.
//!
//! 90 of GW2EI's 90 `LogData.DetectLogic` cases are
//! transcribed; 4 were skipped (below). By category:
//!
//!   fractal              12
//!   golem                10
//!   open_world           1
//!   raid_encounter       25
//!   raid_wing            39
//!   story                1
//!   unknown_encounter    1
//!   wvw                  1
//!
//! `name` is `Some(..)` only for the 38 encounters GW2EI names with a
//! constant its `LogLogic.GetLogicName` override returns -- multi-boss
//! fights ("Twin Largos"), event encounters ("Siege the Stronghold") and
//! the strikes it names after the instance ("Harvest Temple"). For every
//! other id, GW2EI's DEFAULT rule applies -- the fight is named after the
//! boss's own agent name, read from the log's agent table -- so `name` is
//! `None` and [`super::resolve`] does the lookup at parse time.
//!
//! Conditional cases -- ids whose `DetectLogic` arm returns different
//! logics depending on what else is in the log, where this table records
//! only the fall-through one: Dhuum, GadgetTheDragonVoid1, GadgetTheDragonVoid2, McLeodTheSilent, VoidMelter, Xera.
//!
//! Skipped:
//!   AiKeeperOfThePeak (name only)                GetLogicName override is not a single constant return
//!   Instance (name only)                         GetLogicName override is not a single constant return
//!   WorldVersusWorld (name only)                 GetLogicName override is not a single constant return
//!   WorldVersusWorld (sub_category only)         WvWLogic assigns SubCategory conditionally (ArmisticeBastion, BlueAlpineBorderlands, EdgeOfTheMists, EternalBattlegrounds, GreenAlpineBorderlands, GuildHall, ObsidianSanctum, RedDesertBorderlands)
//!
//! Entries are sorted by `trigger_id` so lookups can binary-search.

/// One encounter identity, keyed by arcdps's header trigger id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Encounter {
    /// The evtc header's `boss_id` ([`crate::evtc::RawHeader::boss_id`]).
    pub trigger_id: u32,
    /// GW2EI's `TargetID` enum member, e.g. `"Gorseval"`. Diagnostic only --
    /// it is the join key back into GW2EI's source, not a display name.
    pub member: &'static str,
    /// The `LogLogic` subclass GW2EI hands this id to, e.g. `"TwinLargos"`.
    /// Also diagnostic: two ids sharing a logic are the same fight.
    pub logic: &'static str,
    /// `"raid_wing"`, `"fractal"`, `"raid_encounter"`, `"golem"`, ... --
    /// GW2EI's own `LogCategory`, lowercased. This is what
    /// [`crate::model::Encounter::kind`] carries.
    pub category: &'static str,
    /// GW2EI's `SubLogCategory`, e.g. `"SpiritVale"` -- the wing/fractal
    /// grouping, when it declares one.
    pub sub_category: Option<&'static str>,
    /// The fixed name GW2EI gives this fight, when it does not name it
    /// after the boss agent. `None` means "use the boss's agent name".
    pub name: Option<&'static str>,
}

/// The encounter `trigger_id` identifies, or `None` when GW2EI has no
/// logic for it -- an unsupported or brand-new boss, which
/// [`super::resolve`] still names from the agent table.
pub fn lookup(trigger_id: u32) -> Option<&'static Encounter> {
    ENCOUNTERS
        .binary_search_by_key(&trigger_id, |e| e.trigger_id)
        .ok()
        .map(|i| &ENCOUNTERS[i])
}

/// Every encounter identity GW2EI declares, sorted by `trigger_id`.
pub const ENCOUNTERS: &[Encounter] = &[
    Encounter { trigger_id: 1, member: "WorldVersusWorld", logic: "WvWLogic", category: "wvw", sub_category: None, name: None },
    Encounter { trigger_id: 2, member: "Instance", logic: "UnknownInstanceLogic", category: "unknown_encounter", sub_category: Some("UnknownEncounter"), name: None },
    Encounter { trigger_id: 1378, member: "GadgetTheDragonVoid2", logic: "HarvestTemple", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Harvest Temple") },
    Encounter { trigger_id: 15375, member: "Sabetha", logic: "Sabetha", category: "raid_wing", sub_category: Some("SpiritVale"), name: None },
    Encounter { trigger_id: 15415, member: "WallOfGhosts", logic: "SpiritRace", category: "raid_wing", sub_category: Some("SpiritVale"), name: Some("Spirit Race") },
    Encounter { trigger_id: 15429, member: "Gorseval", logic: "Gorseval", category: "raid_wing", sub_category: Some("SpiritVale"), name: None },
    Encounter { trigger_id: 15438, member: "ValeGuardian", logic: "ValeGuardian", category: "raid_wing", sub_category: Some("SpiritVale"), name: None },
    Encounter { trigger_id: 15884, member: "Mordremoth", logic: "Mordremoth", category: "story", sub_category: Some("Story"), name: None },
    Encounter { trigger_id: 16088, member: "Berg", logic: "BanditTrio", category: "raid_wing", sub_category: Some("SalvationPass"), name: Some("Bandit Trio") },
    Encounter { trigger_id: 16115, member: "Matthias", logic: "Matthias", category: "raid_wing", sub_category: Some("SalvationPass"), name: None },
    Encounter { trigger_id: 16123, member: "Slothasor", logic: "Slothasor", category: "raid_wing", sub_category: Some("SalvationPass"), name: None },
    Encounter { trigger_id: 16125, member: "Narella", logic: "BanditTrio", category: "raid_wing", sub_category: Some("SalvationPass"), name: Some("Bandit Trio") },
    Encounter { trigger_id: 16137, member: "Zane", logic: "BanditTrio", category: "raid_wing", sub_category: Some("SalvationPass"), name: Some("Bandit Trio") },
    Encounter { trigger_id: 16169, member: "MassiveGolem10M", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16174, member: "ConditionGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16176, member: "PowerGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16177, member: "AvgGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16178, member: "MassiveGolem1M", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16198, member: "VitalGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16199, member: "StdGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16202, member: "MassiveGolem4M", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 16235, member: "KeepConstruct", logic: "KeepConstruct", category: "raid_wing", sub_category: Some("StrongholdOfTheFaithful"), name: None },
    Encounter { trigger_id: 16246, member: "Xera", logic: "Xera", category: "raid_wing", sub_category: Some("StrongholdOfTheFaithful"), name: None },
    Encounter { trigger_id: 16247, member: "HauntingStatue", logic: "TwistedCastle", category: "raid_wing", sub_category: Some("StrongholdOfTheFaithful"), name: Some("Twisted Castle") },
    Encounter { trigger_id: 16253, member: "McLeodTheSilent", logic: "Escort", category: "raid_wing", sub_category: Some("StrongholdOfTheFaithful"), name: Some("Siege the Stronghold") },
    Encounter { trigger_id: 16948, member: "Ensolyss", logic: "Ensolyss", category: "fractal", sub_category: Some("Nightmare"), name: None },
    Encounter { trigger_id: 17021, member: "MAMA", logic: "MAMA", category: "fractal", sub_category: Some("Nightmare"), name: None },
    Encounter { trigger_id: 17028, member: "Siax", logic: "Siax", category: "fractal", sub_category: Some("Nightmare"), name: None },
    Encounter { trigger_id: 17154, member: "Deimos", logic: "Deimos", category: "raid_wing", sub_category: Some("BastionOfThePenitent"), name: None },
    Encounter { trigger_id: 17172, member: "MursaatOverseer", logic: "MursaatOverseer", category: "raid_wing", sub_category: Some("BastionOfThePenitent"), name: None },
    Encounter { trigger_id: 17188, member: "Samarog", logic: "Samarog", category: "raid_wing", sub_category: Some("BastionOfThePenitent"), name: None },
    Encounter { trigger_id: 17194, member: "Cairn", logic: "Cairn", category: "raid_wing", sub_category: Some("BastionOfThePenitent"), name: Some("Cairn") },
    Encounter { trigger_id: 17632, member: "Skorvald", logic: "Skorvald", category: "fractal", sub_category: Some("ShatteredObservatory"), name: None },
    Encounter { trigger_id: 17759, member: "Arkk", logic: "Arkk", category: "fractal", sub_category: Some("ShatteredObservatory"), name: None },
    Encounter { trigger_id: 17949, member: "Artsariiv", logic: "Artsariiv", category: "fractal", sub_category: Some("ShatteredObservatory"), name: None },
    Encounter { trigger_id: 19450, member: "Dhuum", logic: "Dhuum", category: "raid_wing", sub_category: Some("HallOfChains"), name: None },
    Encounter { trigger_id: 19536, member: "EaterOfSouls", logic: "StatueOfDeath", category: "raid_wing", sub_category: Some("HallOfChains"), name: Some("Statue of Death") },
    Encounter { trigger_id: 19645, member: "MedGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 19651, member: "EyeOfJudgement", logic: "StatueOfDarkness", category: "raid_wing", sub_category: Some("HallOfChains"), name: Some("Statue of Darkness") },
    Encounter { trigger_id: 19676, member: "LGolem", logic: "Golem", category: "golem", sub_category: Some("Golem"), name: None },
    Encounter { trigger_id: 19691, member: "BrokenKing", logic: "StatueOfIce", category: "raid_wing", sub_category: Some("HallOfChains"), name: Some("Statue of Ice") },
    Encounter { trigger_id: 19767, member: "SoullessHorror", logic: "SoullessHorror", category: "raid_wing", sub_category: Some("HallOfChains"), name: None },
    Encounter { trigger_id: 19828, member: "Desmina", logic: "River", category: "raid_wing", sub_category: Some("HallOfChains"), name: Some("River of Souls") },
    Encounter { trigger_id: 19844, member: "EyeOfFate", logic: "StatueOfDarkness", category: "raid_wing", sub_category: Some("HallOfChains"), name: Some("Statue of Darkness") },
    Encounter { trigger_id: 20934, member: "Qadim", logic: "Qadim", category: "raid_wing", sub_category: Some("MythwrightGambit"), name: None },
    Encounter { trigger_id: 21089, member: "Kenut", logic: "TwinLargos", category: "raid_wing", sub_category: Some("MythwrightGambit"), name: Some("Twin Largos") },
    Encounter { trigger_id: 21105, member: "Nikare", logic: "TwinLargos", category: "raid_wing", sub_category: Some("MythwrightGambit"), name: Some("Twin Largos") },
    Encounter { trigger_id: 21285, member: "AncientInvokedHydra", logic: "Qadim", category: "raid_wing", sub_category: Some("MythwrightGambit"), name: None },
    Encounter { trigger_id: 21333, member: "Freezie", logic: "Freezie", category: "raid_encounter", sub_category: None, name: None },
    Encounter { trigger_id: 21964, member: "Sabir", logic: "Sabir", category: "raid_wing", sub_category: Some("TheKeyOfAhdashim"), name: None },
    Encounter { trigger_id: 22000, member: "QadimThePeerless", logic: "QadimThePeerless", category: "raid_wing", sub_category: Some("TheKeyOfAhdashim"), name: None },
    Encounter { trigger_id: 22006, member: "Adina", logic: "Adina", category: "raid_wing", sub_category: Some("TheKeyOfAhdashim"), name: None },
    Encounter { trigger_id: 22154, member: "IcebroodConstruct", logic: "IcebroodConstruct", category: "raid_encounter", sub_category: Some("Grothmar"), name: None },
    Encounter { trigger_id: 22343, member: "VoiceOfTheFallen", logic: "SuperKodanBrothers", category: "raid_encounter", sub_category: Some("Bjora"), name: Some("Super Kodan Brothers") },
    Encounter { trigger_id: 22481, member: "ClawOfTheFallen", logic: "SuperKodanBrothers", category: "raid_encounter", sub_category: Some("Bjora"), name: Some("Super Kodan Brothers") },
    Encounter { trigger_id: 22492, member: "FraenirOfJormag", logic: "FraenirOfJormag", category: "raid_encounter", sub_category: Some("Bjora"), name: None },
    Encounter { trigger_id: 22521, member: "Boneskinner", logic: "Boneskinner", category: "raid_encounter", sub_category: Some("Bjora"), name: None },
    Encounter { trigger_id: 22711, member: "WhisperOfJormag", logic: "WhisperOfJormag", category: "raid_encounter", sub_category: Some("Bjora"), name: None },
    Encounter { trigger_id: 22836, member: "VariniaStormsounder", logic: "ColdWar", category: "raid_encounter", sub_category: Some("Drizzlewood"), name: None },
    Encounter { trigger_id: 23254, member: "AiKeeperOfThePeak", logic: "AiKeeperOfThePeak", category: "fractal", sub_category: Some("SunquaPeak"), name: None },
    Encounter { trigger_id: 23957, member: "Ankka", logic: "XunlaiJadeJunkyard", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Xunlai Jade Junkyard") },
    Encounter { trigger_id: 24033, member: "MaiTrinRaid", logic: "AetherbladeHideout", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Aetherblade Hideout") },
    Encounter { trigger_id: 24223, member: "VoidMelter", logic: "HarvestTemple", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Harvest Temple") },
    Encounter { trigger_id: 24266, member: "MinisterLiCM", logic: "KainengOverlook", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Kaineng Overlook") },
    Encounter { trigger_id: 24375, member: "VoidAmalgamate", logic: "HarvestTemple", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Harvest Temple") },
    Encounter { trigger_id: 24485, member: "MinisterLi", logic: "KainengOverlook", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Kaineng Overlook") },
    Encounter { trigger_id: 25413, member: "PrototypeVermilion", logic: "OldLionsCourt", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Old Lion's Court") },
    Encounter { trigger_id: 25414, member: "PrototypeVermilionCM", logic: "OldLionsCourt", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Old Lion's Court") },
    Encounter { trigger_id: 25415, member: "PrototypeArsenite", logic: "OldLionsCourt", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Old Lion's Court") },
    Encounter { trigger_id: 25416, member: "PrototypeArseniteCM", logic: "OldLionsCourt", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Old Lion's Court") },
    Encounter { trigger_id: 25419, member: "PrototypeIndigo", logic: "OldLionsCourt", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Old Lion's Court") },
    Encounter { trigger_id: 25423, member: "PrototypeIndigoCM", logic: "OldLionsCourt", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Old Lion's Court") },
    Encounter { trigger_id: 25577, member: "KanaxaiScytheOfHouseAurkusCM", logic: "Kanaxai", category: "fractal", sub_category: Some("SilentSurf"), name: None },
    Encounter { trigger_id: 25705, member: "Dagda", logic: "CosmicObservatory", category: "raid_encounter", sub_category: Some("SotO"), name: Some("Cosmic Observatory") },
    Encounter { trigger_id: 25989, member: "Cerus", logic: "TempleOfFebe", category: "raid_encounter", sub_category: Some("SotO"), name: Some("Temple of Febe") },
    Encounter { trigger_id: 26226, member: "DeimosLonelyTower", logic: "CerusAndDeimos", category: "fractal", sub_category: Some("LonelyTower"), name: Some("Cerus and Deimos") },
    Encounter { trigger_id: 26231, member: "EparchLonelyTower", logic: "Eparch", category: "fractal", sub_category: Some("LonelyTower"), name: Some("Eparch") },
    Encounter { trigger_id: 26257, member: "CerusLonelyTower", logic: "CerusAndDeimos", category: "fractal", sub_category: Some("LonelyTower"), name: Some("Cerus and Deimos") },
    Encounter { trigger_id: 26712, member: "Ura", logic: "UraTheSteamshrieker", category: "raid_wing", sub_category: Some("MountBalrior"), name: None },
    Encounter { trigger_id: 26725, member: "Greer", logic: "GreerTheBlightbringer", category: "raid_wing", sub_category: Some("MountBalrior"), name: None },
    Encounter { trigger_id: 26774, member: "Decima", logic: "DecimaTheStormsinger", category: "raid_wing", sub_category: Some("MountBalrior"), name: None },
    Encounter { trigger_id: 26867, member: "DecimaCM", logic: "DecimaTheStormsinger", category: "raid_wing", sub_category: Some("MountBalrior"), name: None },
    Encounter { trigger_id: 27010, member: "WhisperingShadow", logic: "WhisperingShadow", category: "fractal", sub_category: Some("Kinfall"), name: None },
    Encounter { trigger_id: 27124, member: "KelaSeneschalOfWaves", logic: "GuardiansGlade", category: "raid_encounter", sub_category: Some("VisionsOfEternity"), name: Some("Guardian's Glade") },
    Encounter { trigger_id: 35552, member: "SooWonOW", logic: "SooWon", category: "open_world", sub_category: Some("OpenWorld"), name: None },
    Encounter { trigger_id: 43488, member: "GadgetTheDragonVoid1", logic: "HarvestTemple", category: "raid_encounter", sub_category: Some("Cantha"), name: Some("Harvest Temple") },
    Encounter { trigger_id: 43974, member: "ConjuredAmalgamate", logic: "ConjuredAmalgamate", category: "raid_wing", sub_category: Some("MythwrightGambit"), name: None },
    Encounter { trigger_id: 44885, member: "ConjuredAmalgamate_CHINA", logic: "ConjuredAmalgamate", category: "raid_wing", sub_category: Some("MythwrightGambit"), name: None },
    Encounter { trigger_id: 47188, member: "EtherealBarrierGadget", logic: "SpiritRace", category: "raid_wing", sub_category: Some("SpiritVale"), name: Some("Spirit Race") },
    Encounter { trigger_id: 48133, member: "EtherealBarrierGadget_CHINA", logic: "SpiritRace", category: "raid_wing", sub_category: Some("SpiritVale"), name: Some("Spirit Race") },
];
