#!/usr/bin/env node
// Patches napi-rs's generated `index.d.ts` (M5 Task 2) to reference the
// hand-maintained `types.d.ts` `Report` interface for `parseFile`/
// `parseBuffer`'s return type.
//
// Why this exists: every exported function in `src/lib.rs` returns a plain
// `serde_json::Value` (see that file's module doc), so napi's dts
// generator -- which only sees Rust function *signatures*, not the actual
// runtime JSON shape -- can only ever emit `any` for those two return
// types. `types.d.ts` hand-transcribes `axilog_schema::Report`'s real
// field layout; this script is what wires that type onto the *generated*
// `index.d.ts` (which `npm run build`/`npm run build:debug` re-run and
// overwrite from scratch every time, wiping any hand-edit) so the fix
// survives every rebuild instead of needing to be manually reapplied.
// (`parseFileEi`'s return value is a materially different, larger EI-JSON
// shape -- not typed here, stays `any`.)
//
// Idempotent: safe to run against an already-patched file (re-running
// `npm run build` twice in a row does not double-insert the import or
// no-op the replace).
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const dir = dirname(fileURLToPath(import.meta.url))
const dtsPath = join(dir, '..', 'index.d.ts')

let src = readFileSync(dtsPath, 'utf8')
const before = src

const IMPORT_LINE = "import type { Report } from './types'"
if (!src.includes(IMPORT_LINE)) {
  const headerMarker = '/* auto-generated by NAPI-RS */\n'
  if (src.includes(headerMarker)) {
    src = src.replace(headerMarker, `${headerMarker}${IMPORT_LINE}\n`)
  } else {
    // Header line missing/changed upstream: fall back to prepending.
    src = `${IMPORT_LINE}\n${src}`
  }
}

// M9 Task 2: `parseFile`/`parseBuffer` gained a trailing optional `opts`
// parameter (`ParseOptions`, for the opt-in `replay` block) -- match up to
// the closing `)` generically rather than the old fixed-arity signature, so
// this still finds (and only swaps the return type of) the right
// declaration regardless of the exact parameter list napi-rs emits.
src = src.replace(
  /export declare function parseFile\(([^)]*)\): any/,
  'export declare function parseFile($1): Report',
)
src = src.replace(
  /export declare function parseBuffer\(([^)]*)\): any/,
  'export declare function parseBuffer($1): Report',
)

if (src !== before) {
  writeFileSync(dtsPath, src)
  console.log(`patch-dts: updated ${dtsPath}`)
} else {
  console.log(`patch-dts: ${dtsPath} already up to date`)
}
