// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `elementalist` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 62982,
        source: "CatalystHelper",
        trigger: Trigger::BuffGain { buff_id: 62726 },
        min_gw2_build: 122479,
        max_gw2_build: 147734,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5492,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5585 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5493,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5586 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5494,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5575 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5495,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5580 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 34736,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5739 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 34772,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5741 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 34637,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5740 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 34714,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5742 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5539,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 5539 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5635,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGive { buff_id: 5582 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 182824,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5641,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5640 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5635,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 76507 },
        min_gw2_build: 182824,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 22572,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 22572 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5543,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 5543 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5536,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 5536 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5572,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 5572 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 56883,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 56883 },
        origin: CastOrigin::Unconditional,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13334,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 13334 },
        origin: CastOrigin::Unconditional,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 56885,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 56885 },
        origin: CastOrigin::Unconditional,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24305,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 24305 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24060,
        source: "ElementalistHelper",
        trigger: Trigger::ExtHealing { skill_id: 24060 },
        origin: CastOrigin::Unconditional,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24061,
        source: "ElementalistHelper",
        trigger: Trigger::ExtHealing { skill_id: 24061 },
        origin: CastOrigin::Unconditional,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24299,
        source: "ElementalistHelper",
        trigger: Trigger::ExtHealing { skill_id: 24299 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 25499,
        source: "ElementalistHelper",
        trigger: Trigger::MinionCommand { species_id: 21221 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 25492,
        source: "ElementalistHelper",
        trigger: Trigger::MinionCommand { species_id: 21049 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 25480,
        source: "ElementalistHelper",
        trigger: Trigger::MinionCommand { species_id: 6522 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 25498,
        source: "ElementalistHelper",
        trigger: Trigger::MinionCommand { species_id: 6523 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5561,
        source: "ElementalistHelper",
        trigger: Trigger::Damage { skill_id: 5561 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5780,
        source: "ElementalistHelper",
        trigger: Trigger::Missile { skill_id: 5780 },
        icd: 900,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 73037,
        source: "ElementalistHelper",
        trigger: Trigger::BuffGain { buff_id: 73071 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76643,
        source: "EvokerHelper",
        trigger: Trigger::MinionCast { skill_id: 76882 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77225,
        source: "EvokerHelper",
        trigger: Trigger::MinionCast { skill_id: 76709 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77370,
        source: "EvokerHelper",
        trigger: Trigger::MinionCast { skill_id: 76803 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77226,
        source: "EvokerHelper",
        trigger: Trigger::MinionCast { skill_id: 76925 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 40183,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 42086 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44926,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 45097 },
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44612,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 42683 },
        min_gw2_build: 82356,
        max_gw2_build: 203989,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 80231,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 42683 },
        min_gw2_build: 203989,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43470,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 43470 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-5i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-5i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-6i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-6i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-7i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-7i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-8i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-8i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41166,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 41166 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-9i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-9i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-10i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-10i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-11i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-11i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-12i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-12i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42264,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 42264 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-13i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-13i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-14i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-14i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-15i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-15i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-16i32) as u32),
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: ((-16i32) as u32) },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44857,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 44857 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72916,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 72961 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72916,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 79372 },
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 73104,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 73073 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 73104,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 79347 },
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72914,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 73023 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72914,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 79346 },
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 73052,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 72979 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 73052,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 79364 },
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72906,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 72996 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72906,
        source: "WeaverHelper",
        trigger: Trigger::BuffGain { buff_id: 79373 },
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
];
