// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `engineer` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 77018,
        source: "AmalgamHelper",
        trigger: Trigger::BuffGain { buff_id: 77362 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77163,
        source: "AmalgamHelper",
        trigger: Trigger::BuffGain { buff_id: 77283 },
        min_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 59562,
        source: "EngineerHelper",
        trigger: Trigger::BuffLoss { buff_id: 59579 },
        origin: CastOrigin::Trait,
        min_gw2_build: 102321,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5861,
        source: "EngineerHelper",
        trigger: Trigger::BuffGain { buff_id: 5863 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5825,
        source: "EngineerHelper",
        trigger: Trigger::BuffGain { buff_id: 5833 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 5977,
        source: "EngineerHelper",
        trigger: Trigger::BuffGain { buff_id: 5976 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 6154,
        source: "EngineerHelper",
        trigger: Trigger::Damage { skill_id: 6154 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 6126,
        source: "EngineerHelper",
        trigger: Trigger::Damage { skill_id: 6126 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 73064,
        source: "EngineerHelper",
        trigger: Trigger::Damage { skill_id: 73064 },
        icd: 1100,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29889,
        source: "EngineerHelper",
        trigger: Trigger::Missile { skill_id: 29889 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41612,
        source: "EngineerHelper",
        trigger: Trigger::Damage { skill_id: 41612 },
        origin: CastOrigin::Trait,
        time_offset: -2000,
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 6178,
        source: "EngineerHelper",
        trigger: Trigger::Missile { skill_id: 6178 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42938,
        source: "HolosmithHelper",
        trigger: Trigger::BuffGain { buff_id: 43708 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41123,
        source: "HolosmithHelper",
        trigger: Trigger::BuffLoss { buff_id: 43708 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43937,
        source: "HolosmithHelper",
        trigger: Trigger::BuffGain { buff_id: 41037 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41218,
        source: "HolosmithHelper",
        trigger: Trigger::BuffGain { buff_id: 43066 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43630,
        source: "HolosmithHelper",
        trigger: Trigger::Damage { skill_id: 43630 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42163,
        source: "HolosmithHelper",
        trigger: Trigger::Missile { skill_id: 42163 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45732,
        source: "HolosmithHelper",
        trigger: Trigger::Missile { skill_id: 45732 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63095,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63334 },
        not_accurate: true,
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63050,
        source: "MechanistHelper",
        trigger: Trigger::Damage { skill_id: 63050 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63334,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63334 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63365,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63365 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63188,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63188 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63367,
        source: "MechanistHelper",
        trigger: Trigger::BuffGain { buff_id: 63238 },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63345,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63345 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63121,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63121 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63141,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63141 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63236,
        source: "MechanistHelper",
        trigger: Trigger::MinionCast { skill_id: 63236 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63185,
        source: "MechanistHelper",
        trigger: Trigger::Missile { skill_id: 63185 },
        minions: true,
        ..FinderDef::DEFAULT
    },
];
