// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `guardian` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 41714,
        source: "FirebrandHelper",
        trigger: Trigger::ExtHealing { skill_id: 41714 },
        enable: &[Enable::NoEffectData, Enable::HasExtHealing],
        min_gw2_build: 115190,
        max_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46618,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 46618 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 115190,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45082,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 45082 },
        enable: &[Enable::NoEffectData],
        min_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46616,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 46616 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 115190,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42924,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 42924 },
        enable: &[Enable::NoEffectData],
        min_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46148,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 46618 },
        enable: &[Enable::NoEffectData],
        min_gw2_build: 115190,
        max_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42360,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 42360 },
        enable: &[Enable::NoEffectData],
        min_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44008,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 44008 },
        enable: &[Enable::NoEffectData],
        min_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44080,
        source: "FirebrandHelper",
        trigger: Trigger::Damage { skill_id: 46508 },
        enable: &[Enable::NoEffectData],
        min_gw2_build: 115190,
        max_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44364,
        source: "FirebrandHelper",
        trigger: Trigger::BuffGain { buff_id: 44291 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 137943,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41780,
        source: "FirebrandHelper",
        trigger: Trigger::BuffGain { buff_id: 41493 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 137943,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42259,
        source: "FirebrandHelper",
        trigger: Trigger::BuffGain { buff_id: 42404 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 137943,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41380,
        source: "FirebrandHelper",
        trigger: Trigger::BuffLoss { buff_id: 44291 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 137943,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41380,
        source: "FirebrandHelper",
        trigger: Trigger::BuffLoss { buff_id: 41493 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 137943,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41380,
        source: "FirebrandHelper",
        trigger: Trigger::BuffLoss { buff_id: 42404 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 137943,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9082,
        source: "GuardianHelper",
        trigger: Trigger::BuffGain { buff_id: 9123 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9104,
        source: "GuardianHelper",
        trigger: Trigger::BuffGain { buff_id: 9103 },
        icd: 0,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9247,
        source: "GuardianHelper",
        trigger: Trigger::Damage { skill_id: 9247 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9245,
        source: "GuardianHelper",
        trigger: Trigger::Damage { skill_id: 9245 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9101,
        source: "GuardianHelper",
        trigger: Trigger::Damage { skill_id: 9101 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30255,
        source: "GuardianHelper",
        trigger: Trigger::Damage { skill_id: 30255 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 21795,
        source: "GuardianHelper",
        trigger: Trigger::Damage { skill_id: 21795 },
        origin: CastOrigin::Trait,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 159951,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13629,
        source: "GuardianHelper",
        trigger: Trigger::ExtHealing { skill_id: 13629 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        min_gw2_build: 159951,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 22499,
        source: "GuardianHelper",
        trigger: Trigger::Damage { skill_id: 22499 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13594,
        source: "GuardianHelper",
        trigger: Trigger::ExtHealing { skill_id: 13594 },
        origin: CastOrigin::Unconditional,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77073,
        source: "LuminaryHelper",
        trigger: Trigger::BuffGain { buff_id: 77142 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76616,
        source: "LuminaryHelper",
        trigger: Trigger::BuffLoss { buff_id: 77142 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77321,
        source: "LuminaryHelper",
        trigger: Trigger::BuffGain { buff_id: 76868 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77300,
        source: "LuminaryHelper",
        trigger: Trigger::BuffGain { buff_id: 76736 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76813,
        source: "LuminaryHelper",
        trigger: Trigger::BuffGain { buff_id: 77095 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76730,
        source: "LuminaryHelper",
        trigger: Trigger::BuffLoss { buff_id: 77265 },
        ..FinderDef::DEFAULT
    },
];
