// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `mesmer` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 29830,
        source: "ChronomancerHelper",
        trigger: Trigger::BuffGain { buff_id: 30136 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30747,
        source: "ChronomancerHelper",
        trigger: Trigger::BuffLoss { buff_id: 30136 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79359,
        source: "ChronomancerHelper",
        trigger: Trigger::Damage { skill_id: 79359 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10197,
        source: "MesmerHelper",
        trigger: Trigger::BuffGain { buff_id: 10198 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10199,
        source: "MesmerHelper",
        trigger: Trigger::BuffGain { buff_id: 16553 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30192,
        source: "MesmerHelper",
        trigger: Trigger::Damage { skill_id: 30192 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10212,
        source: "MesmerHelper",
        trigger: Trigger::Damage { skill_id: 10212 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 115190,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10211,
        source: "MesmerHelper",
        trigger: Trigger::Damage { skill_id: 10211 },
        min_gw2_build: 115190,
        max_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10212,
        source: "MesmerHelper",
        trigger: Trigger::Damage { skill_id: 10212 },
        min_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10213,
        source: "MesmerHelper",
        trigger: Trigger::ExtHealing { skill_id: 10213 },
        enable: &[Enable::HasExtHealing],
        min_gw2_build: 115190,
        max_gw2_build: 141374,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71792,
        source: "MesmerHelper",
        trigger: Trigger::BuffGive { buff_id: 71890 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45449,
        source: "MirageHelper",
        trigger: Trigger::Damage { skill_id: 45449 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-17i32) as u32),
        source: "MirageHelper",
        trigger: Trigger::BuffGain { buff_id: 40408 },
        ..FinderDef::DEFAULT
    },
];
