// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! The transcribed `InstantCastFinder` catalog.
//!
//! Extracted from 70 GW2EI source files: **649** finder
//! constructions considered, **571** transcribed,
//! **78** skipped. Every skip carries a named reason (below);
//! nothing is approximated, because a finder that loses an
//! unrepresentable checker would fire on events Elite Insights never
//! counts -- worse than a missing finder, not better.
//!
//! Skips by reason:
//!
//! - 70 x arbitrary `.UsingChecker(lambda)` predicate
//! - 4 x the barrier extension is not decoded by this project
//! - 4 x bespoke subclass with log-specific state
//!
//! Constructions by subclass:
//!
//! - 190 x `BuffGainCastFinder`
//! - 112 x `EffectCastFinder`
//! - 86 x `MinionCommandCastFinder`
//! - 74 x `DamageCastFinder`
//! - 60 x `EffectCastFinderByDst`
//! - 32 x `EXTHealingCastFinder`
//! - 30 x `BuffLossCastFinder`
//! - 21 x `BuffGiveCastFinder`
//! - 12 x `MinionCastCastFinder`
//! - 11 x `MissileCastFinder`
//! - 11 x `MinionSpawnCastFinder`
//! - 4 x `EXTBarrierCastFinder`
//! - 4 x `BandTogetherCastFinder`
//! - 2 x `BreakbarDamageCastFinder`

pub mod elementalist;
pub mod engineer;
pub mod guardian;
pub mod mesmer;
pub mod necromancer;
pub mod ranger;
pub mod revenant;
pub mod shared;
pub mod thief;
pub mod warrior;

use crate::analysis::instant_cast::model::FinderDef;

/// Every transcribed finder, in catalog order.
pub fn all() -> Vec<&'static FinderDef> {
    [
        elementalist::FINDERS,
        engineer::FINDERS,
        guardian::FINDERS,
        mesmer::FINDERS,
        necromancer::FINDERS,
        ranger::FINDERS,
        revenant::FINDERS,
        shared::FINDERS,
        thief::FINDERS,
        warrior::FINDERS,
    ]
    .iter()
    .flat_map(|s| s.iter())
    .collect()
}
