// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `necromancer` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 62567,
        source: "HarbingerHelper",
        trigger: Trigger::BuffGain { buff_id: 59964 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62540,
        source: "HarbingerHelper",
        trigger: Trigger::BuffLoss { buff_id: 59964 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62660,
        source: "HarbingerHelper",
        trigger: Trigger::Damage { skill_id: 62660 },
        origin: CastOrigin::Trait,
        enable: &[Enable::NoEffectData],
        min_gw2_build: 118697,
        max_gw2_build: 203989,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 80215,
        source: "HarbingerHelper",
        trigger: Trigger::BuffGain { buff_id: 80215 },
        min_gw2_build: 203989,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10574,
        source: "NecromancerHelper",
        trigger: Trigger::BuffGain { buff_id: 790 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10585,
        source: "NecromancerHelper",
        trigger: Trigger::BuffLoss { buff_id: 790 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13907,
        source: "NecromancerHelper",
        trigger: Trigger::Damage { skill_id: 13907 },
        origin: CastOrigin::Unconditional,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13906,
        source: "NecromancerHelper",
        trigger: Trigger::Damage { skill_id: 13906 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 38767,
        source: "NecromancerHelper",
        trigger: Trigger::Damage { skill_id: 38767 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29560,
        source: "NecromancerHelper",
        trigger: Trigger::Damage { skill_id: 29560 },
        origin: CastOrigin::Unconditional,
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10583,
        source: "NecromancerHelper",
        trigger: Trigger::BuffGain { buff_id: 10582 },
        min_gw2_build: 94051,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10685,
        source: "NecromancerHelper",
        trigger: Trigger::BuffGain { buff_id: 15083 },
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 94051,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10685,
        source: "NecromancerHelper",
        trigger: Trigger::BuffGain { buff_id: 53476 },
        min_gw2_build: 94051,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13863,
        source: "NecromancerHelper",
        trigger: Trigger::ExtHealing { skill_id: 13863 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10570,
        source: "NecromancerHelper",
        trigger: Trigger::MinionCommand { species_id: 1458 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10590,
        source: "NecromancerHelper",
        trigger: Trigger::MinionCommand { species_id: 5673 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 10600,
        source: "NecromancerHelper",
        trigger: Trigger::MinionCommand { species_id: 19464 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30792,
        source: "ReaperHelper",
        trigger: Trigger::BuffGain { buff_id: 29446 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30961,
        source: "ReaperHelper",
        trigger: Trigger::BuffLoss { buff_id: 29446 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29958,
        source: "ReaperHelper",
        trigger: Trigger::BuffGain { buff_id: 30129 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29414,
        source: "ReaperHelper",
        trigger: Trigger::Damage { skill_id: 29414 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30670,
        source: "ReaperHelper",
        trigger: Trigger::Damage { skill_id: 30670 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29604,
        source: "ReaperHelper",
        trigger: Trigger::Damage { skill_id: 29604 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77238,
        source: "RitualistHelper",
        trigger: Trigger::BuffGain { buff_id: 76958 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76933,
        source: "RitualistHelper",
        trigger: Trigger::BuffLoss { buff_id: 76958 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76752,
        source: "RitualistHelper",
        trigger: Trigger::BuffGive { buff_id: 77011 },
        min_gw2_build: 186019,
        max_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76752,
        source: "RitualistHelper",
        trigger: Trigger::BuffGain { buff_id: 78624 },
        min_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77022,
        source: "RitualistHelper",
        trigger: Trigger::BuffGive { buff_id: 76565 },
        min_gw2_build: 186019,
        max_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77022,
        source: "RitualistHelper",
        trigger: Trigger::BuffGain { buff_id: 78272 },
        min_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76941,
        source: "RitualistHelper",
        trigger: Trigger::BuffGive { buff_id: 76764 },
        min_gw2_build: 186019,
        max_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76941,
        source: "RitualistHelper",
        trigger: Trigger::BuffGain { buff_id: 78313 },
        min_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76783,
        source: "RitualistHelper",
        trigger: Trigger::Damage { skill_id: 76783 },
        origin: CastOrigin::Unconditional,
        min_gw2_build: 186019,
        max_gw2_build: 190000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79105,
        source: "RitualistHelper",
        trigger: Trigger::BuffGain { buff_id: 76783 },
        origin: CastOrigin::Unconditional,
        min_gw2_build: 190000,
        max_gw2_build: 192224,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76783,
        source: "RitualistHelper",
        trigger: Trigger::Damage { skill_id: 76783 },
        origin: CastOrigin::Unconditional,
        min_gw2_build: 192224,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 40274,
        source: "ScourgeHelper",
        trigger: Trigger::BuffGain { buff_id: 42311 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 40813,
        source: "ScourgeHelper",
        trigger: Trigger::Damage { skill_id: 46808 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44428,
        source: "ScourgeHelper",
        trigger: Trigger::Damage { skill_id: 40071 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44663,
        source: "ScourgeHelper",
        trigger: Trigger::BuffGain { buff_id: 40052 },
        checks: &[
            Check::Duration { duration: 6000, epsilon: 150 },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 54870,
        source: "ScourgeHelper",
        trigger: Trigger::BuffGain { buff_id: 40052 },
        checks: &[
            Check::Duration { duration: 3500, epsilon: 150 },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43626,
        source: "ScourgeHelper",
        trigger: Trigger::BuffGain { buff_id: 43626 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
];
