// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `ranger` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

/// `EffectGUIDs.DruidBloodMoon`.
const G_DRUID_BLOOD_MOON: [u8; 16] = [0x28, 0x34, 0x6F, 0x32, 0xFD, 0x19, 0x9C, 0x4B, 0x8F, 0x9B, 0x15, 0x43, 0x8F, 0x27, 0xA4, 0x34];
/// `EffectGUIDs.DruidGlyphOfEquality`.
const G_DRUID_GLYPH_OF_EQUALITY: [u8; 16] = [0x9B, 0x8A, 0x1B, 0xE5, 0x54, 0x45, 0x0B, 0x48, 0x99, 0xB6, 0x4F, 0x75, 0x79, 0xDF, 0x0A, 0x8C];
/// `EffectGUIDs.DruidGlyphOfEqualityCA`.
const G_DRUID_GLYPH_OF_EQUALITY_C_A: [u8; 16] = [0x74, 0x87, 0x05, 0x58, 0xC4, 0x3E, 0x47, 0x47, 0x95, 0x5C, 0x57, 0x3C, 0xAA, 0xC6, 0x30, 0xA7];
/// `EffectGUIDs.DruidSeedOfLife`.
const G_DRUID_SEED_OF_LIFE: [u8; 16] = [0x19, 0xC4, 0xFA, 0x17, 0xA3, 0x8E, 0x7E, 0x47, 0x80, 0x72, 0x27, 0x99, 0xB4, 0x8B, 0xF2, 0xBE];
/// `EffectGUIDs.GaleshotDismissCycloneBow`.
const G_GALESHOT_DISMISS_CYCLONE_BOW: [u8; 16] = [0x92, 0x42, 0xD1, 0x0B, 0x4F, 0x04, 0x27, 0x4E, 0xB6, 0xE9, 0xEB, 0xCD, 0xB2, 0x26, 0x21, 0x81];
/// `EffectGUIDs.GaleshotSummonCycloneBow`.
const G_GALESHOT_SUMMON_CYCLONE_BOW: [u8; 16] = [0xC1, 0xF1, 0xE3, 0x86, 0xCC, 0x1E, 0x0B, 0x44, 0x84, 0x35, 0x26, 0x9D, 0xBB, 0xFB, 0x34, 0xD7];
/// `EffectGUIDs.RangerLightningReflexes`.
const G_RANGER_LIGHTNING_REFLEXES: [u8; 16] = [0x3C, 0xF1, 0xD1, 0x22, 0x8C, 0xBC, 0x37, 0x40, 0xAA, 0x33, 0xED, 0xA3, 0x57, 0xEA, 0xBE, 0xD4];
/// `EffectGUIDs.RangerQuickeningZephyr`.
const G_RANGER_QUICKENING_ZEPHYR: [u8; 16] = [0xB2, 0x31, 0x57, 0xC5, 0x15, 0x07, 0x2E, 0x46, 0xB5, 0x51, 0x44, 0x19, 0xB0, 0xF9, 0x23, 0xB7];
/// `EffectGUIDs.RangerSignetOfRenewal`.
const G_RANGER_SIGNET_OF_RENEWAL: [u8; 16] = [0xEA, 0x98, 0x96, 0xA8, 0x1D, 0xDF, 0x48, 0x43, 0xB1, 0x8D, 0xBF, 0x6E, 0xE4, 0xF2, 0x5E, 0x18];
/// `EffectGUIDs.RangerSignetOfTheHunt`.
const G_RANGER_SIGNET_OF_THE_HUNT: [u8; 16] = [0x1A, 0x38, 0xCA, 0xE7, 0x2C, 0x2F, 0x16, 0x4B, 0xA3, 0x81, 0x54, 0x41, 0xCA, 0x64, 0x3A, 0x20];
/// `EffectGUIDs.SoulbeastEternalBond`.
const G_SOULBEAST_ETERNAL_BOND: [u8; 16] = [0xBF, 0x0A, 0x5B, 0x11, 0xA4, 0x07, 0x6A, 0x4F, 0x98, 0xC6, 0xE1, 0xD6, 0x55, 0xD5, 0x07, 0xB1];
/// `EffectGUIDs.UntamedEnvelopingHaze`.
const G_UNTAMED_ENVELOPING_HAZE: [u8; 16] = [0xF2, 0xB1, 0xB6, 0x19, 0x70, 0xFC, 0x59, 0x41, 0x8A, 0xC0, 0x49, 0xBF, 0x3A, 0x07, 0xFF, 0xD4];
/// `EffectGUIDs.UntamedMutateConditions`.
const G_UNTAMED_MUTATE_CONDITIONS: [u8; 16] = [0xD7, 0xDC, 0xD4, 0xAB, 0xF9, 0xE4, 0xA7, 0x49, 0x95, 0x0A, 0xF0, 0x17, 0x5E, 0x02, 0xEA, 0x06];
/// `EffectGUIDs.UntamedRendingVines`.
const G_UNTAMED_RENDING_VINES: [u8; 16] = [0x2C, 0x40, 0xB0, 0x74, 0x11, 0x11, 0x44, 0x4F, 0x98, 0x89, 0x5A, 0x65, 0x8A, 0x7F, 0x97, 0x8F];
/// `EffectGUIDs.UntamedUnnaturalTraversal`.
const G_UNTAMED_UNNATURAL_TRAVERSAL: [u8; 16] = [0x8D, 0x36, 0x80, 0x6A, 0x69, 0x0A, 0x54, 0x42, 0xA9, 0x83, 0x30, 0x8E, 0xDC, 0xEC, 0xB0, 0x18];
/// `EffectGUIDs.UntamedVenomousOutburst`.
const G_UNTAMED_VENOMOUS_OUTBURST: [u8; 16] = [0x60, 0xBE, 0x46, 0x92, 0xA4, 0x55, 0xB1, 0x40, 0xA0, 0x5A, 0xD7, 0x94, 0xBF, 0x47, 0x53, 0xF6];

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 31869,
        source: "DruidHelper",
        trigger: Trigger::BuffGain { buff_id: 31508 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31411,
        source: "DruidHelper",
        trigger: Trigger::BuffLoss { buff_id: 31508 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31406,
        source: "DruidHelper",
        trigger: Trigger::Effect { guid: &G_DRUID_SEED_OF_LIFE, by_dst: false },
        checks: &[
            Check::Spec { party: Party::Key, specs: &["Druid"], base: false, negated: false },
        ],
        min_gw2_build: 135242,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31658,
        source: "DruidHelper",
        trigger: Trigger::Damage { skill_id: 31658 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31401,
        source: "DruidHelper",
        trigger: Trigger::Effect { guid: &G_DRUID_GLYPH_OF_EQUALITY_C_A, by_dst: true },
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Druid"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31658,
        source: "DruidHelper",
        trigger: Trigger::Effect { guid: &G_DRUID_GLYPH_OF_EQUALITY, by_dst: false },
        checks: &[
            Check::Spec { party: Party::Key, specs: &["Druid"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31749,
        source: "DruidHelper",
        trigger: Trigger::Effect { guid: &G_DRUID_BLOOD_MOON, by_dst: false },
        origin: CastOrigin::Trait,
        checks: &[
            Check::Spec { party: Party::Key, specs: &["Druid"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76787,
        source: "GaleshotHelper",
        trigger: Trigger::Effect { guid: &G_GALESHOT_SUMMON_CYCLONE_BOW, by_dst: false },
        swap_snap: SwapSnap::Before,
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Galeshot"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77213,
        source: "GaleshotHelper",
        trigger: Trigger::Effect { guid: &G_GALESHOT_DISMISS_CYCLONE_BOW, by_dst: true },
        swap_snap: SwapSnap::Before,
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Galeshot"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76905,
        source: "GaleshotHelper",
        trigger: Trigger::Damage { skill_id: 76905 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12633,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 33902 },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79348,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 79348 },
        minions: true,
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12633,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 56923 },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12537,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 12536 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29703,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 29703 },
        origin: CastOrigin::Trait,
        swap_snap: SwapSnap::After,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12574,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 12574 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13980,
        source: "RangerHelper",
        trigger: Trigger::ExtHealing { skill_id: 13980 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30784,
        source: "RangerHelper",
        trigger: Trigger::ExtHealing { skill_id: 30784 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14016,
        source: "RangerHelper",
        trigger: Trigger::ExtHealing { skill_id: 14016 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 34309,
        source: "RangerHelper",
        trigger: Trigger::BuffGive { buff_id: 34236 },
        not_accurate: true,
        icd: 1100,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12494,
        source: "RangerHelper",
        trigger: Trigger::Effect { guid: &G_RANGER_LIGHTNING_REFLEXES, by_dst: false },
        checks: &[
            Check::Spec { party: Party::Key, specs: &["Ranger"], base: true, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12550,
        source: "RangerHelper",
        trigger: Trigger::Effect { guid: &G_RANGER_QUICKENING_ZEPHYR, by_dst: true },
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Ranger"], base: true, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12502,
        source: "RangerHelper",
        trigger: Trigger::Effect { guid: &G_RANGER_SIGNET_OF_RENEWAL, by_dst: true },
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Ranger"], base: true, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12542,
        source: "RangerHelper",
        trigger: Trigger::Effect { guid: &G_RANGER_SIGNET_OF_THE_HUNT, by_dst: true },
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Ranger"], base: true, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-28i32) as u32),
        source: "RangerHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[3827, 4425, 4426, 5581, 5582, 6043, 6044, 6045, 6849, 6850, 6883, 6884, 6885, 6886, 6887, 6888, 6889, 6898, 6968, 7336, 7926, 7927, 7928, 7932, 7948, 7949, 7975, 7976, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8013, 8014, 8015, 8016, 8035, 8041, 8042, 9458, 10022, 11491, 15380, 15399, 15402, 15418, 15436, 18119, 18688, 19005, 19104, 19166, 24203, 24298, 24796, 25652, 26147, 26220, 26628, 26851, 27259, 27687] },
        not_accurate: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71002,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 25652 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12744,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8035 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12722,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8003 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 20975,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 10022 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12721,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8002 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12722,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6045 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12722,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8004 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63716,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 25131 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 78873,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 27259 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31367,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15418 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12716,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6043 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12717,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7336 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12718,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7976 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12715,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 4425 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12714,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7975 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71688,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26147 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72843,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26220 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12675,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5581 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12703,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5581 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12679,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7949 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12704,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7949 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12674,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7948 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12702,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7948 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12696,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6889 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12697,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6889 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12701,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6850 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12700,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6850 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 16426,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 11491 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 16427,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 11491 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12698,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6888 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12699,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6888 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12670,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5582 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12695,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5582 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12681,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6849 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12658,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 3827 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12693,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6044 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12656,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6044 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31451,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15380 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 65109,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 24298 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12680,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7932 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42963,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 19005 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42180,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 19166 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 74314,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26628 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41156,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 18688 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44980,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 18119 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 75783,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26851 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12748,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8041 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12749,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8042 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12748,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 9458 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12713,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6883 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12708,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6884 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12712,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6885 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12711,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6886 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12709,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6887 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12754,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8013 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12732,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8016 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12756,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8015 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12755,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8014 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 66622,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 24203 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43636,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 19104 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79766,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 27687 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12757,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6968 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 65418,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 24796 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31568,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15402 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12730,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8005 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12731,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8007 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12729,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8006 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12729,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8008 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12664,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7928 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12685,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7927 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12688,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7927 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12666,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 4426 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12691,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 4426 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12687,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6898 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12690,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6898 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12667,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7926 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12689,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7926 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31639,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15436 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31459,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15399 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 40272 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 40272 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 44932 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 44932 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 44693 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 44693 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 41720 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 41720 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 40069 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 40069 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45789,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGive { buff_id: 41815 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45970,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGive { buff_id: 45038 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 40498,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGive { buff_id: 44651 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45479,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 43266 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 59554,
        source: "SoulbeastHelper",
        trigger: Trigger::Effect { guid: &G_SOULBEAST_ETERNAL_BOND, by_dst: false },
        checks: &[
            Check::Spec { party: Party::Key, specs: &["Soulbeast"], base: false, negated: false },
        ],
        min_gw2_build: 135242,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63344,
        source: "UntamedHelper",
        trigger: Trigger::BuffGain { buff_id: 63145 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63147,
        source: "UntamedHelper",
        trigger: Trigger::BuffGain { buff_id: 63317 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 69193,
        source: "UntamedHelper",
        trigger: Trigger::BuffGain { buff_id: 69193 },
        origin: CastOrigin::Trait,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 182824,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63256,
        source: "UntamedHelper",
        trigger: Trigger::Effect { guid: &G_UNTAMED_MUTATE_CONDITIONS, by_dst: true },
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Untamed"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63195,
        source: "UntamedHelper",
        trigger: Trigger::Effect { guid: &G_UNTAMED_UNNATURAL_TRAVERSAL, by_dst: true },
        checks: &[
            Check::AroundDst { negated: false },
            Check::Spec { party: Party::Other, specs: &["Untamed"], base: false, negated: false },
        ],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63209,
        source: "UntamedHelper",
        trigger: Trigger::Effect { guid: &G_UNTAMED_VENOMOUS_OUTBURST, by_dst: false },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63258,
        source: "UntamedHelper",
        trigger: Trigger::Effect { guid: &G_UNTAMED_RENDING_VINES, by_dst: false },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63094,
        source: "UntamedHelper",
        trigger: Trigger::Effect { guid: &G_UNTAMED_ENVELOPING_HAZE, by_dst: false },
        minions: true,
        ..FinderDef::DEFAULT
    },
];
