// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `ranger` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 31869,
        source: "DruidHelper",
        trigger: Trigger::BuffGain { buff_id: 31508 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31411,
        source: "DruidHelper",
        trigger: Trigger::BuffLoss { buff_id: 31508 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31658,
        source: "DruidHelper",
        trigger: Trigger::Damage { skill_id: 31658 },
        enable: &[Enable::NoEffectData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76905,
        source: "GaleshotHelper",
        trigger: Trigger::Damage { skill_id: 76905 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12633,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 33902 },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79348,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 79348 },
        minions: true,
        min_gw2_build: 193778,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12633,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 56923 },
        minions: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12537,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 12536 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29703,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 29703 },
        origin: CastOrigin::Trait,
        swap_snap: SwapSnap::After,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12574,
        source: "RangerHelper",
        trigger: Trigger::BuffGain { buff_id: 12574 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13980,
        source: "RangerHelper",
        trigger: Trigger::ExtHealing { skill_id: 13980 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30784,
        source: "RangerHelper",
        trigger: Trigger::ExtHealing { skill_id: 30784 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14016,
        source: "RangerHelper",
        trigger: Trigger::ExtHealing { skill_id: 14016 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 34309,
        source: "RangerHelper",
        trigger: Trigger::BuffGive { buff_id: 34236 },
        not_accurate: true,
        icd: 1100,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-28i32) as u32),
        source: "RangerHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[3827, 4425, 4426, 5581, 5582, 6043, 6044, 6045, 6849, 6850, 6883, 6884, 6885, 6886, 6887, 6888, 6889, 6898, 6968, 7336, 7926, 7927, 7928, 7932, 7948, 7949, 7975, 7976, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8013, 8014, 8015, 8016, 8035, 8041, 8042, 9458, 10022, 11491, 15380, 15399, 15402, 15418, 15436, 18119, 18688, 19005, 19104, 19166, 24203, 24298, 24796, 25652, 26147, 26220, 26628, 26851, 27259, 27687] },
        not_accurate: true,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71002,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 25652 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12744,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8035 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12722,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8003 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 20975,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 10022 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12721,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8002 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12722,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6045 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12722,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8004 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63716,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 25131 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 78873,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 27259 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31367,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15418 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12716,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6043 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12717,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7336 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12718,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7976 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12715,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 4425 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12714,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7975 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71688,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26147 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 72843,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26220 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12675,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5581 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12703,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5581 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12679,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7949 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12704,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7949 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12674,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7948 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12702,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7948 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12696,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6889 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12697,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6889 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12701,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6850 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12700,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6850 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 16426,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 11491 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 16427,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 11491 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12698,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6888 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12699,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6888 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12670,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5582 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12695,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 5582 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12681,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6849 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12658,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 3827 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12693,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6044 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12656,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6044 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31451,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15380 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 65109,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 24298 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12680,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7932 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42963,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 19005 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42180,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 19166 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 74314,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26628 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41156,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 18688 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 44980,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 18119 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 75783,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 26851 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12748,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8041 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12749,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8042 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12748,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 9458 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12713,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6883 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12708,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6884 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12712,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6885 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12711,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6886 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12709,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6887 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12754,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8013 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12732,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8016 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12756,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8015 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12755,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8014 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 66622,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 24203 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43636,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 19104 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79766,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 27687 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12757,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6968 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 65418,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 24796 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31568,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15402 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12730,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8005 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12731,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8007 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12729,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8006 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12729,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 8008 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12664,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7928 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12685,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7927 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12688,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7927 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12666,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 4426 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12691,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 4426 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12687,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6898 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12690,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 6898 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12667,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7926 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12689,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 7926 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31639,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15436 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31459,
        source: "RangerHelper",
        trigger: Trigger::MinionCommand { species_id: 15399 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 40272 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 40272 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 44932 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 44932 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 44693 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 44693 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 41720 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 41720 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 42944,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 40069 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43014,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffLoss { buff_id: 40069 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45789,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGive { buff_id: 41815 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45970,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGive { buff_id: 45038 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 40498,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGive { buff_id: 44651 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45479,
        source: "SoulbeastHelper",
        trigger: Trigger::BuffGain { buff_id: 43266 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63344,
        source: "UntamedHelper",
        trigger: Trigger::BuffGain { buff_id: 63145 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63147,
        source: "UntamedHelper",
        trigger: Trigger::BuffGain { buff_id: 63317 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 69193,
        source: "UntamedHelper",
        trigger: Trigger::BuffGain { buff_id: 69193 },
        origin: CastOrigin::Trait,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 182824,
        ..FinderDef::DEFAULT
    },
];
