// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `revenant` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 76610,
        source: "ConduitHelper",
        trigger: Trigger::BuffGain { buff_id: 77234 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77021,
        source: "ConduitHelper",
        trigger: Trigger::Damage { skill_id: 77021 },
        origin: CastOrigin::Unconditional,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28085,
        source: "HeraldHelper",
        trigger: Trigger::BuffGain { buff_id: 27732 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 29371,
        source: "HeraldHelper",
        trigger: Trigger::BuffGain { buff_id: 29275 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28379,
        source: "HeraldHelper",
        trigger: Trigger::BuffGain { buff_id: 28036 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 27014,
        source: "HeraldHelper",
        trigger: Trigger::BuffGain { buff_id: 28243 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 26644,
        source: "HeraldHelper",
        trigger: Trigger::BuffGain { buff_id: 27376 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 27760,
        source: "HeraldHelper",
        trigger: Trigger::BuffGain { buff_id: 27983 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46857,
        source: "HeraldHelper",
        trigger: Trigger::Damage { skill_id: 46857 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 41858,
        source: "RenegadeHelper",
        trigger: Trigger::BuffGain { buff_id: 44272 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46849,
        source: "RenegadeHelper",
        trigger: Trigger::Damage { skill_id: 46849 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28134,
        source: "RevenantHelper",
        trigger: Trigger::BuffGain { buff_id: 27890 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28494,
        source: "RevenantHelper",
        trigger: Trigger::BuffGain { buff_id: 27928 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28419,
        source: "RevenantHelper",
        trigger: Trigger::BuffGain { buff_id: 27205 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28195,
        source: "RevenantHelper",
        trigger: Trigger::BuffGain { buff_id: 27972 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 27107,
        source: "RevenantHelper",
        trigger: Trigger::BuffGain { buff_id: 27581 },
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28382,
        source: "RevenantHelper",
        trigger: Trigger::BuffLoss { buff_id: 27581 },
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 26557,
        source: "RevenantHelper",
        trigger: Trigger::BuffGain { buff_id: 27273 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 26956,
        source: "RevenantHelper",
        trigger: Trigger::BuffLoss { buff_id: 27273 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 26693,
        source: "RevenantHelper",
        trigger: Trigger::BuffLoss { buff_id: 28001 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 59591,
        source: "RevenantHelper",
        trigger: Trigger::Damage { skill_id: 59591 },
        origin: CastOrigin::Unconditional,
        min_gw2_build: 102321,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46854,
        source: "RevenantHelper",
        trigger: Trigger::Damage { skill_id: 46854 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46843,
        source: "RevenantHelper",
        trigger: Trigger::Damage { skill_id: 46843 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46856,
        source: "RevenantHelper",
        trigger: Trigger::Damage { skill_id: 46856 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 28388,
        source: "RevenantHelper",
        trigger: Trigger::Damage { skill_id: 28388 },
        origin: CastOrigin::Trait,
        min_gw2_build: 94051,
        max_gw2_build: 102321,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 46847,
        source: "RevenantHelper",
        trigger: Trigger::ExtHealing { skill_id: 46847 },
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62749,
        source: "VindicatorHelper",
        trigger: Trigger::BuffGain { buff_id: 62919 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62705,
        source: "VindicatorHelper",
        trigger: Trigger::Damage { skill_id: 62705 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62687,
        source: "VindicatorHelper",
        trigger: Trigger::BuffGain { buff_id: 62864 },
        ..FinderDef::DEFAULT
    },
];
