// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `shared` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: ((-32i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::BuffLoss { buff_id: 69855 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-40i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::BuffLoss { buff_id: 73955 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9432,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9432 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9431,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9431 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9433,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9433 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9292,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9292 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9284,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9284 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 26261,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 26261 },
        origin: CastOrigin::Gear,
        icd: 500,
        enable: &[Enable::NoMissileData],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9425,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9425 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9427,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9427 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9428,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 9428 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 33022,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 33022 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43930,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 43930 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9703,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 9703 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9440,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 9440 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9441,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 9441 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9417,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 9417 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-38i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 9416 },
        origin: CastOrigin::Gear,
        min_gw2_build: 93543,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9422,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 9422 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 33719,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 33719 },
        origin: CastOrigin::Gear,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 93543,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24242,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 24242 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24244,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 24244 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 24241,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 24241 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9293,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 9293 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 20461,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 20461 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 20462,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 20462 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9298,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 9298 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9413,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 9413 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9288,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 9288 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9457,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 9457 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 9458,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 9458 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 26261,
        source: "ProfHelper",
        trigger: Trigger::Missile { skill_id: 26261 },
        origin: CastOrigin::Gear,
        icd: 500,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-42i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[21314] },
        origin: CastOrigin::Gear,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 150431,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-43i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[8836] },
        origin: CastOrigin::Gear,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 150431,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-44i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[8837] },
        origin: CastOrigin::Gear,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 150431,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-45i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[8838] },
        origin: CastOrigin::Gear,
        min_gw2_build: START_OF_LIFE,
        max_gw2_build: 150431,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79423,
        source: "ProfHelper",
        trigger: Trigger::Damage { skill_id: 79423 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 69961,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 69961 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71217,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 71217 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71431,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 71431 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 69620,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 69620 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76326,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 76326 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76351,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 76351 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79482,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 79482 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79393,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 79393 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71202,
        source: "ProfHelper",
        trigger: Trigger::BuffGive { buff_id: 71139 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 70806,
        source: "ProfHelper",
        trigger: Trigger::BuffGive { buff_id: 70806 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 70350,
        source: "ProfHelper",
        trigger: Trigger::BuffGive { buff_id: 70350 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79435,
        source: "ProfHelper",
        trigger: Trigger::BuffGive { buff_id: 79435 },
        origin: CastOrigin::Gear,
        icd: 100,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71356,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 71356 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71382,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 71382 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 70001,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 70001 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 70765,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 70765 },
        origin: CastOrigin::Gear,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-46i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[21314] },
        origin: CastOrigin::Gear,
        min_gw2_build: 171452,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-47i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[8836] },
        origin: CastOrigin::Gear,
        min_gw2_build: 171452,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-48i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[8837] },
        origin: CastOrigin::Gear,
        min_gw2_build: 171452,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-49i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::MinionSpawn { species_ids: &[8838] },
        origin: CastOrigin::Gear,
        min_gw2_build: 171452,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 71051,
        source: "ProfHelper",
        trigger: Trigger::Missile { skill_id: 71051 },
        origin: CastOrigin::Gear,
        icd: 1000,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 70196,
        source: "ProfHelper",
        trigger: Trigger::Missile { skill_id: 70196 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79505,
        source: "ProfHelper",
        trigger: Trigger::Missile { skill_id: 79505 },
        origin: CastOrigin::Gear,
        icd: 100,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 80072,
        source: "ProfHelper",
        trigger: Trigger::Missile { skill_id: 80072 },
        origin: CastOrigin::Gear,
        icd: 100,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-59i32) as u32),
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 79938 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 79640,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 79640 },
        origin: CastOrigin::Gear,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 49128,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 50216 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 52571,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 51762 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 54032,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 54118 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 61081,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 60469 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12836,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 12836 },
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12825,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 12825 },
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12826,
        source: "ProfHelper",
        trigger: Trigger::ExtHealing { skill_id: 12826 },
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12815,
        source: "ProfHelper",
        trigger: Trigger::BreakbarDamage { skill_id: 12815 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 35155,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 34978 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 20851,
        source: "ProfHelper",
        trigger: Trigger::BuffGain { buff_id: 20852 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 12318,
        source: "ProfHelper",
        trigger: Trigger::BreakbarDamage { skill_id: 12318 },
        ..FinderDef::DEFAULT
    },
];
