// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `thief` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 77230,
        source: "AntiquaryHelper",
        trigger: Trigger::BuffGain { buff_id: 76659 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 77230,
        source: "AntiquaryHelper",
        trigger: Trigger::BuffGain { buff_id: 77252 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76744,
        source: "AntiquaryHelper",
        trigger: Trigger::BuffGain { buff_id: 77054 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76744,
        source: "AntiquaryHelper",
        trigger: Trigger::BuffGain { buff_id: 76574 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76879,
        source: "AntiquaryHelper",
        trigger: Trigger::BuffGain { buff_id: 77086 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 76784,
        source: "AntiquaryHelper",
        trigger: Trigger::BuffGain { buff_id: 76921 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31129,
        source: "DaredevilHelper",
        trigger: Trigger::BuffGain { buff_id: 33162 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31267,
        source: "DaredevilHelper",
        trigger: Trigger::BuffGain { buff_id: 32200 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 31187,
        source: "DaredevilHelper",
        trigger: Trigger::BuffGain { buff_id: 32931 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63155,
        source: "SpecterHelper",
        trigger: Trigger::BuffGain { buff_id: 63239 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 63251,
        source: "SpecterHelper",
        trigger: Trigger::BuffLoss { buff_id: 63239 },
        swap_snap: SwapSnap::Before,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13002,
        source: "ThiefHelper",
        trigger: Trigger::BuffGain { buff_id: 13135 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13014,
        source: "ThiefHelper",
        trigger: Trigger::Damage { skill_id: 13014 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13015,
        source: "ThiefHelper",
        trigger: Trigger::Damage { skill_id: 13015 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13046,
        source: "ThiefHelper",
        trigger: Trigger::BuffGain { buff_id: 44597 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13093,
        source: "ThiefHelper",
        trigger: Trigger::BuffGive { buff_id: 13094 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13096,
        source: "ThiefHelper",
        trigger: Trigger::BuffGive { buff_id: 13095 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13055,
        source: "ThiefHelper",
        trigger: Trigger::BuffGive { buff_id: 13054 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 49052,
        source: "ThiefHelper",
        trigger: Trigger::BuffGive { buff_id: 49083 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 13037,
        source: "ThiefHelper",
        trigger: Trigger::BuffGive { buff_id: 13036 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 16435,
        source: "ThiefHelper",
        trigger: Trigger::BuffGain { buff_id: 57031 },
        ..FinderDef::DEFAULT
    },
];
