// @generated by scripts/gen_instant_cast_catalog.py -- do not edit.
//! Instant-cast finders transcribed from GW2EI's `warrior` profession
//! helpers. See `super`'s module doc for the extraction accounting.

use crate::analysis::instant_cast::model::*;

pub const FINDERS: &[FinderDef] = &[
    FinderDef {
        skill_id: 31289,
        source: "BerserkerHelper",
        trigger: Trigger::Damage { skill_id: 31289 },
        origin: CastOrigin::Trait,
        enable: &[Enable::NoEffectData],
        min_gw2_build: 97950,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: ((-41i32) as u32),
        source: "BerserkerHelper",
        trigger: Trigger::BuffLoss { buff_id: 29502 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 30435,
        source: "BerserkerHelper",
        trigger: Trigger::BuffGain { buff_id: 29502 },
        min_gw2_build: 135242,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62861,
        source: "BladeswornHelper",
        trigger: Trigger::BuffLoss { buff_id: 62769 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 119939,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62745,
        source: "BladeswornHelper",
        trigger: Trigger::BuffGain { buff_id: 62769 },
        swap_snap: SwapSnap::Before,
        min_gw2_build: 119939,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 62847,
        source: "BladeswornHelper",
        trigger: Trigger::Damage { skill_id: 62847 },
        origin: CastOrigin::Trait,
        min_gw2_build: 119939,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43745,
        source: "SpellbreakerHelper",
        trigger: Trigger::BuffGain { buff_id: 40616 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 43532,
        source: "SpellbreakerHelper",
        trigger: Trigger::BuffGive { buff_id: 42428 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 45534,
        source: "SpellbreakerHelper",
        trigger: Trigger::Damage { skill_id: 45534 },
        origin: CastOrigin::Trait,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14268,
        source: "WarriorHelper",
        trigger: Trigger::Damage { skill_id: 14268 },
        origin: CastOrigin::Unconditional,
        min_gw2_build: 84794,
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14406,
        source: "WarriorHelper",
        trigger: Trigger::BuffGain { buff_id: 14453 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14412,
        source: "WarriorHelper",
        trigger: Trigger::BuffGain { buff_id: 34778 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14392,
        source: "WarriorHelper",
        trigger: Trigger::BuffGain { buff_id: 787 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14410,
        source: "WarriorHelper",
        trigger: Trigger::BuffGain { buff_id: 51664 },
        ..FinderDef::DEFAULT
    },
    FinderDef {
        skill_id: 14282,
        source: "WarriorHelper",
        trigger: Trigger::ExtHealing { skill_id: 14282 },
        origin: CastOrigin::Trait,
        enable: &[Enable::HasExtHealing],
        ..FinderDef::DEFAULT
    },
];
